window.STELLAR_DATA = (() => {
  const palette = { center: '#c92135', inheritance: '#e1b84f', organization: '#9faa68', conflict: '#f0783d', war: '#50b9c9', legacy: '#a979ba', belt: '#f4e2ba', event: '#ef9f4f', text: '#b7a5e7', place: '#8da0ad' };
  const sources = [
    { id: 'stalin-biography', title: '正名：斯大林简传', kind: '专题资料', href: 'biography.html', status: '候选审阅' },
    { id: 'stalin-relations', title: '斯大林局部恒星系', kind: '关系展板', href: 'relations.html', status: '视觉原型' },
    { id: 'stalin-profile', title: '斯大林资料入口', kind: '专题资料', href: 'stalin.html', status: '已发布' },
    { id: 'stalin-industry-section', title: '一五计划与大饥荒', kind: '传记章节', href: 'biography.html#industrialization-famine', status: '作者稿待审' },
    { id: 'stalin-war-section', title: '卫国战争：崩溃与重铸', kind: '传记章节', href: 'biography.html#war', status: '作者稿待审' },
    { id: 'stalin-postwar-section', title: '间章：全民族的慈父', kind: '传记章节', href: 'biography.html#post-stalin', status: '作者稿待审' },
    { id: 'stalin-purge-section', title: '大清洗：对官僚阶级的战争', kind: '传记章节', href: 'biography.html#purge', status: '争议章节待审' },
    { id: 'stalin-institutions-section', title: '两种斯大林：体制为何僵化，治理为何灵活', kind: '传记章节', href: 'biography.html#two-stalins', status: '作者观点待审' }
  ];
  const sourceMap = { stalin:[['post-stalin','p-137'],['industrialization-famine','p-030']], lenin:[['party-manager','p-018']], 'five-year-plans':[['industrialization-famine','p-029'],['industrialization-famine','p-030']], 'collectivization-famine':[['industrialization-famine','p-032'],['industrialization-famine','p-033'],['industrialization-famine','p-034']], industrialization:[['industrialization-famine','p-030'],['industrialization-famine','p-031']], barbarossa:[['war','p-082']], 'great-patriotic-war':[['war','p-082'],['war','p-084'],['war','p-101']], 'moscow-defense':[['war','p-085'],['war','p-086'],['war','p-091']], 'stalingrad-battle':[['war','p-099']], 'yalta-conference':[['softness','p-043']], 'nature-transformation-plan':[['postwar','p-113']], 'forest-belt-plan':[['postwar','p-113']], 'housing-design':[['postwar','p-114']], 'shelter-policy':[['postwar','p-114']], 'consumer-price-cuts':[['postwar','p-115']], 'postwar-price-cuts':[['postwar','p-115']], 'soviet-institutions':[['two-stalins','p-128'],['two-stalins','p-129'],['two-stalins','p-130']], 'bureaucratic-governance':[['postwar','p-105'],['two-stalins','p-136']], 'postwar-reconstruction':[['postwar','p-102'],['postwar','p-117']], 'great-purge':[['purge','p-060'],['purge','p-061'],['purge','p-079']], kirov:[['purge','p-060'],['purge','p-061']], khrushchev:[['post-stalin','p-137'],['post-stalin','p-138'],['post-stalin','p-139']], 'red-army':[['war','p-084'],['war','p-099']], zhukov:[['war','p-086'],['war','p-087'],['war','p-092']] };
  const sourceKinds = { 'historical-record':'历史记录（候选）', 'author-judgment':'作者判断（候选）', 'historical-dramatization':'历史演绎（候选）' };
  const scope = { id: 'stalin-local', title: '斯大林局部恒星系', subtitle: '国际共运人物大星图 · 局部星系 00', description: '以斯大林局部系统验证人物、组织、事件、文本与地点共同导航的图谱语法。每条关系保留类别、时期、来源和审阅状态。', center: 'stalin' };
  const entities = [
    ['stalin','person','斯大林','局部恒星系中心','1878—1953','center','star',34,'苏维埃建设恒星核','把理论继承、党政机器、战争实践、路线斗争与历史遗产连接在同一局部星系。',['俄共（布）','联共（布）','共产国际'],['十月革命后苏维埃建设','社会主义工业化','卫国战争'],['stalin-biography','stalin-profile']],
    ['marx','person','马克思','理论前辈','1818—1883','inheritance','mentor',12,'理论继承星云','马克思主义源流的前置引力源。',['共产主义者同盟','第一国际'],['马克思主义理论源流'],['stalin-biography']],
    ['engels','person','恩格斯','理论前辈','1820—1895','inheritance','mentor',11,'理论继承星云','马克思主义传统的重要整理者与传播者。',['共产主义者同盟','第一国际'],[],['stalin-biography']],
    ['lenin','person','列宁','政治前辈与继承对象','1870—1924','inheritance','mentor',16,'理论继承星云','组织传统、革命国家与理论继承进入斯大林时代的重要节点。',['布尔什维克','俄共（布）','共产国际'],['十月革命','新经济政策'],['stalin-biography']],
    ['trotsky','person','托洛茨基','路线斗争对象','1879—1940','conflict','comet',10,'路线斗争彗云','革命策略、军事组织、工业化与世界革命问题上的分歧对象。',[],['路线斗争','流亡'],['stalin-biography']],
    ['bukharin','person','布哈林','路线斗争对象与牺牲者','','conflict','comet',9,'路线斗争彗云','围绕新经济政策与工业化路线形成的重要争议关系。',[],['新经济政策争议','莫斯科审判'],['stalin-biography']],
    ['zinoviev','person','季诺维也夫','党内路线斗争人物','','conflict','comet',8,'路线斗争彗云','老近卫军与共产国际背景交织的路线斗争节点。',['共产国际'],['莫斯科审判'],['stalin-biography']],
    ['kirov','person','基洛夫','政治事件相关人物','','conflict','planet',11,'路线斗争彗云','其遇刺与宪法改革、大清洗逻辑相关，存在重要历史争议。',[],['基洛夫遇刺'],['stalin-biography']],
    ['tukhachevsky','person','图哈切夫斯基','军事路线与清洗相关人物','','conflict','comet',9,'军事清洗彗云','军事思想、红军整顿与秘密审判相关的争议节点。',[],['军事清洗'],['stalin-biography']],
    ['molotov','person','莫洛托夫','政治执行者','','organization','planet',13,'近轨政治机器','长期参与政治执行、战时领导与外交事务。',['苏联政府','外交人民委员部'],['卫国战争'],['stalin-biography']],
    ['voroshilov','person','伏罗希洛夫','早期军事班底','','organization','planet',12,'近轨组织星群','察里津时期形成的早期军事关联。',[],['察里津'],['stalin-biography']],
    ['budyonny','person','布琼尼','早期军事班底','','organization','planet',10,'近轨组织星群','察里津军事班底关联人物。',[],['察里津'],['stalin-biography']],
    ['beria','person','贝利亚','安全与政治机器人物','','organization','planet',11,'安全机器暗区','安全系统与政治机器中的复杂关系节点。',[],['大清洗'],['stalin-biography']],
    ['yezhov','person','叶若夫','内务系统人物','','organization','moon',6,'安全机器暗区','清洗机器的运作与反噬相关节点。',['内务人民委员部'],['大清洗'],['stalin-biography']],
    ['zhukov','person','朱可夫','战时军事指挥','','war','planet',13,'战争与外交星云','战时军事指挥与权力放权关系的重要节点。',['红军'],['莫斯科保卫战','柏林战役'],['stalin-biography']],
    ['rokossovsky','person','罗科索夫斯基','战时军事指挥','','war','moon',7,'战争与外交星云','清洗后成长起来的军事指挥员之一。',['红军'],['卫国战争'],['stalin-biography']],
    ['konev','person','科涅夫','战时军事指挥','','war','moon',7,'战争与外交星云','战时指挥与红军重组相关节点。',['红军'],['卫国战争'],['stalin-biography']],
    ['churchill','person','丘吉尔','战时外交对象','','war','planet',10,'战争与外交星云','德黑兰会议和第二战场问题相关的外交节点。',[],['德黑兰会议'],['stalin-biography']],
    ['roosevelt','person','罗斯福','战时外交对象','','war','planet',10,'战争与外交星云','反法西斯同盟与战时外交关系节点。',[],['雅尔塔会议'],['stalin-biography']],
    ['hitler','person','希特勒','敌对入侵者','1889—1945','war','comet',10,'战争与外交星云','从局部系统外切入的敌对战争关系。',[],['巴巴罗萨行动','卫国战争'],['stalin-biography']],
    ['khrushchev','person','赫鲁晓夫','后斯大林继承者与否定者','','legacy','planet',12,'后斯大林遗产远云','继承、否定与去斯大林化的遗产节点。',[],['去斯大林化'],['stalin-biography']],
    ['brezhnev','person','勃列日涅夫','体制继承者','','legacy','planet',10,'后斯大林遗产远云','体制继承与停滞相关节点。',[],['停滞时期'],['stalin-biography']],
    ['gorbachev','person','戈尔巴乔夫','体制终结者','','legacy','planet',10,'后斯大林遗产远云','改革尝试与苏联解体相关节点。',[],['苏联解体'],['stalin-biography']],
    ['comintern','organization','共产国际','国际革命组织','1919—1943','organization','moon',6,'国际组织近轨','连接国际共运、世界革命讨论与组织实践的机构节点。',[],['共产国际解散'],['stalin-biography']],
    ['red-army','organization','红军','军事组织','1918—1946','war','asteroid',6,'战争与外交星云','战争动员、军事指挥和群众牺牲的组织性节点。',[],['卫国战争'],['stalin-biography']],
    ['industrialization','event','社会主义工业化','历史事件','1928—1937','event','asteroid',7,'建设脉冲带','五年计划、集体化及其代价应作为独立历史事件阅读。',[],['一五计划','大饥荒'],['stalin-biography']],
    ['great-purge','event','大清洗','历史事件','1936—1938','conflict','asteroid',7,'路线斗争彗云','高度争议的事件节点，应明确区分史实、判断与待审阅材料。',[],['莫斯科审判','军事清洗'],['stalin-biography']],
    ['great-patriotic-war','event','卫国战争','历史事件','1941—1945','war','asteroid',7,'战争与外交星云','战争、军事、外交与民众牺牲的核心事件层。',[],['巴巴罗萨行动','斯大林格勒战役','柏林战役'],['stalin-biography']],
    ['barbarossa','event','巴巴罗萨行动','战争事件','1941','war','asteroid',6,'战争与外交星云','1941年纳粹德国入侵苏联，开启苏德战争的重大军事行动。',['红军'],['卫国战争'],['stalin-war-section']],
    ['foundations-leninism','text','论列宁主义基础','理论文本','1924','inheritance','asteroid',6,'理论继承星云','系统阐述列宁主义基本原理的文本入口。',[],[],['stalin-profile']],
    ['marxism-national-question','text','马克思主义和民族问题','理论文本','1913','inheritance','asteroid',6,'理论继承星云','民族问题理论相关文本入口。',[],[],['stalin-profile']],
    ['moscow','place','莫斯科','地点','','organization','asteroid',5,'组织治理暗云','苏维埃国家治理与战时决策的重要地点入口。',[],[],['stalin-biography']],
    ['soviet-institutions','legacy','苏联制度与国家能力','战后制度遗产','1953—1991','legacy','planet',9,'苏联制度遗产','作者将苏联制度与国家组织能力视为重要家底；本节点记录这一解释路径，不将其作为无争议结论。',[],['国家治理','制度继承'],['stalin-postwar-section']],
    ['postwar-reconstruction','legacy','战后经济与重建','经济遗产','1945—1953','legacy','planet',8,'经济与生活遗产','战后恢复、工业能力与经济状况的综合入口；具体成效及代价需按来源分别审阅。',[],['战后重建'],['stalin-postwar-section']],
    ['housing-design','legacy','标准化住宅建设草案','住房政策遗产','1940—1960','legacy','asteroid',6,'人民生活与建设遗产','资料稿称后来的标准化住宅计划沿用了斯大林时期构想；原始图纸与政策连续性仍需核验。',[],['标准化住宅','赫鲁晓夫楼'],['stalin-postwar-section']],
    ['consumer-price-cuts','legacy','战后消费品降价政策','生活政策遗产','1947—1953','legacy','asteroid',6,'人民生活与建设遗产','资料稿提及战后连续降低部分基本生活品零售价格；具体轮次、商品和实际购买力影响待核验。',[],['零售价格','人民生活'],['stalin-postwar-section']],
    ['nature-transformation-plan','legacy','大自然改造计划','环境政策遗产','1948—1953','legacy','asteroid',6,'环境治理遗产','战后防护林与土地改造计划的专题入口；政策目标、实施范围和长期效果需独立核查。',[],['防护林','土地改造'],['stalin-postwar-section']],
    ['five-year-plans','event','五年计划与工业化','历史事件','1928—1941','event','asteroid',7,'建设脉冲带','集中资源建设工业能力的历史过程，同时涉及社会成本与政策争议。',['国家计划委员会'],['一五计划','二五计划'],['stalin-industry-section']],
    ['collectivization-famine','event','集体化与1932—1933年饥荒','历史事件','1929—1933','conflict','asteroid',7,'路线斗争彗云','涉及集体化、征粮、饥荒及责任解释的重大争议事件，需呈现多类证据和观点。',[],['集体化','1932—1933年饥荒'],['stalin-industry-section']],
    ['moscow-defense','event','莫斯科保卫战','历史事件','1941—1942','war','asteroid',7,'战争与外交星云','战争初期的关键转折事件，与军事指挥、工业转移和国家动员相连。',['红军'],['巴巴罗萨行动','卫国战争'],['stalin-war-section']],
    ['stalingrad-battle','event','斯大林格勒战役','历史事件','1942—1943','war','asteroid',7,'战争与外交星云','卫国战争的重要转折战役，关联前线指挥、后方生产与民众动员。',['红军'],['卫国战争'],['stalin-war-section']],
    ['yalta-conference','event','雅尔塔会议','历史事件','1945','war','asteroid',6,'战争与外交星云','盟国领导人战时外交会议，关系到战后安排与国际秩序讨论。',[],['反法西斯同盟','战后安排'],['stalin-war-section']],
    ['postwar-price-cuts','event','战后多轮零售价格调整','历史事件','1947—1953','legacy','asteroid',6,'人民生活与建设遗产','记录战后基本消费品价格政策及其目标、执行和实际影响。',[],['零售价格','战后重建'],['stalin-postwar-section']],
    ['shelter-policy','event','战后住房建设方案','历史事件','1945—1953','legacy','asteroid',6,'人民生活与建设遗产','记录战后住房标准化构想及其后续政策关联，具体继承关系待档案核验。',[],['住房建设','标准化住宅'],['stalin-postwar-section']],
    ['forest-belt-plan','event','防护林与土地改造计划','历史事件','1948—1953','legacy','asteroid',6,'环境治理遗产','记录防护林计划的政策形成、实施范围与生态效果。',[],['环境治理','防护林'],['stalin-postwar-section']],
    ['bureaucratic-governance','legacy','官僚治理与制度惯性','制度遗产','1930—1991','legacy','planet',8,'苏联制度遗产','用于追踪国家行政能力、官僚结构、制度调整及后续僵化解释之间的关系。',[],['制度治理','官僚主义'],['stalin-institutions-section','stalin-purge-section']]
  ].map(([id, kind, name, role, years, group, celestialType, size, nebula, summary, organizations, events, sourceIds]) => { const dates = String(years || '').match(/\d{4}/g) || []; const activeFrom = dates[0] ? Number(dates[0]) : null; const activeTo = dates[1] ? Number(dates[1]) : activeFrom; const deathDate = kind === 'person' && dates.length > 1 ? activeTo : null; return { id, kind, name, role, years, activeFrom, activeTo, deathDate, group, celestialType, size, nebula, summary, organizations, events, sourceIds, lifecycle: kind === 'person' && deathDate ? 'white-dwarf' : kind === 'event' ? 'pulse' : 'active', legacyIds: id === 'stalin' ? ['soviet-institutions','postwar-reconstruction','housing-design','consumer-price-cuts','nature-transformation-plan','bureaucratic-governance'] : [], perspectiveNote: group === 'legacy' ? '作者观点路径；需独立史料核验，不代表已定论。' : '', reviewStatus: group === 'legacy' ? '需来源核验' : id === 'great-purge' || id === 'kirov' || id === 'tukhachevsky' || id === 'collectivization-famine' ? '需复核' : '候选整理' }; });
  const relations = [
    ['stalin','marx','inheritance','理论源流远距引力','1818—1953',.72],['stalin','engels','inheritance','理论传统与整理传播','1820—1953',.66],['stalin','lenin','inheritance','政治继承与组织传统','1917—1953',.95],
    ['stalin','trotsky','conflict','路线斗争与军事分歧','1918—1940',.9,true],['stalin','bukharin','conflict','经济路线分歧与清洗牺牲','1924—1938',.82,true],['stalin','kirov','conflict','政治事件与改革争议','1934—1936',.58,true],['stalin','tukhachevsky','conflict','军队整顿与军事路线','1937',.7,true],
    ['stalin','voroshilov','alliance','察里津军事班底','1918—1953',.72],['stalin','budyonny','alliance','察里津军事班底','1918—1953',.62],['stalin','molotov','organization','政治执行与战时领导','1920—1953',.86],['stalin','beria','organization','安全与政治机器','1938—1953',.74],['stalin','yezhov','organization','清洗机器与反噬','1936—1939',.68,true],['stalin','comintern','organization','国际革命组织关系','1922—1943',.7],
    ['stalin','zhukov','military','战时放权与军事指挥','1941—1945',.82],['stalin','hitler','military','卫国战争中的敌对关系','1941—1945',.88],['stalin','churchill','diplomacy','德黑兰会议与战时外交','1941—1945',.7],['stalin','roosevelt','diplomacy','反法西斯同盟','1941—1945',.66],['zhukov','rokossovsky','military','共同战时指挥','1941—1945',.56],['zhukov','konev','military','共同战时指挥','1941—1945',.56],['great-patriotic-war','red-army','event-participation','战争动员与作战','1941—1945',.95],['stalin','great-patriotic-war','event-participation','战争领导与决策','1941—1945',.94],
    ['stalin','industrialization','event-participation','工业化与国家建设','1928—1937',.92,true],['stalin','great-purge','event-participation','清洗与制度争议','1936—1938',.92,true],['stalin','foundations-leninism','authorship','理论文本作者','1924',.8],['stalin','marxism-national-question','authorship','理论文本作者','1913',.8],['stalin','moscow','place-association','国家治理与决策中心','1918—1953',.7],
    ['stalin','khrushchev','legacy','继承、否定与去斯大林化','1953—1964',.88,true],['stalin','brezhnev','legacy','体制继承与停滞','1964—1982',.62],['stalin','gorbachev','legacy','改革与解体的后果','1985—1991',.64],
    ['stalin','soviet-institutions','legacy','制度与国家能力遗产','1953—1991',.82,true],['stalin','postwar-reconstruction','legacy','战后重建与经济遗产','1945—1953',.76],['stalin','housing-design','legacy','住房草案与后续住宅建设关联','1945—1960',.62,true],['stalin','consumer-price-cuts','legacy','战后基本消费品价格政策','1947—1953',.62],['stalin','nature-transformation-plan','legacy','防护林与环境治理计划','1948—1953',.62,true],['stalin','bureaucratic-governance','legacy','官僚治理、能力与制度惯性','1930—1953',.86,true],
    ['five-year-plans','industrialization','event-causation','计划建设与工业化进程','1928—1941',.9],['five-year-plans','collectivization-famine','event-consequence','工业化与集体化政策的交织及其代价','1929—1933',.95,true],['stalin','five-year-plans','event-participation','计划与工业化决策','1928—1941',.9,true],['stalin','collectivization-famine','event-participation','集体化政策责任与历史争议','1929—1933',.95,true],
    ['barbarossa','great-patriotic-war','event-causation','巴巴罗萨行动开启苏德战争','1941',.98],['great-patriotic-war','moscow-defense','event-causation','战争初期与莫斯科保卫战','1941—1942',.9],['moscow-defense','stalingrad-battle','event-consequence','战场转折与斯大林格勒战役','1942—1943',.92],['yalta-conference','great-patriotic-war','event-context','盟国外交与战后安排','1945',.78],['stalin','moscow-defense','event-participation','国家与军事决策','1941—1942',.8],['stalin','stalingrad-battle','event-participation','战时最高统帅与战略决策','1942—1943',.82],['stalin','yalta-conference','event-participation','盟国首脑会议','1945',.78],
    ['postwar-reconstruction','consumer-price-cuts','event-consequence','战后生活政策与价格调整','1947—1953',.7],['postwar-reconstruction','shelter-policy','event-consequence','战后住房建设构想','1945—1953',.68],['nature-transformation-plan','forest-belt-plan','event-causation','防护林计划作为环境治理项目','1948—1953',.78,true],['khrushchev','housing-design','legacy','后续住宅建设与草案关联','1953—1960',.56,true],['khrushchev','consumer-price-cuts','legacy','政策延续、调整与社会影响','1953—1964',.46,true],['soviet-institutions','bureaucratic-governance','legacy','制度能力与官僚惯性并存','1930—1991',.86,true],['stalin','soviet-institutions','legacy','国家制度与组织能力遗产','1922—1953',.85,true],
    ['great-patriotic-war','postwar-reconstruction','event-consequence','战争结束后的恢复与重建','1945—1953',.82],['great-patriotic-war','soviet-institutions','event-impact','战争动员对战后国家能力的影响','1941—1953',.68,true],['great-purge','bureaucratic-governance','event-impact','清洗对组织结构与制度运行的长期影响','1936—1991',.86,true],['collectivization-famine','industrialization','event-context','工业化进程中的集体化背景与代价','1928—1937',.9,true],['stalin','postwar-price-cuts','event-participation','战后价格政策决策','1947—1953',.68,true],['stalin','shelter-policy','event-participation','战后住房方案决策','1945—1953',.62,true],['stalin','forest-belt-plan','event-participation','防护林与土地改造计划','1948—1953',.62,true]
  ].map(([source,target,type,label,period,strength,controversy=false]) => ({ source,target,type,label,period,strength,controversy,sourceIds:type.startsWith('event-')?['stalin-biography']:type==='legacy'?['stalin-postwar-section','stalin-institutions-section']:['stalin-biography'],reviewStatus: controversy ? '需复核' : '候选整理', coneRole:type==='event-causation'?'precursor':type==='event-participation'?'participant':type==='event-consequence'?'consequence':type==='legacy'?'long-term-impact':'context' }));
  const layout = { marx:[535,248,-.22], engels:[565,267,-.20], lenin:[345,286,-.16], molotov:[170,16,-.08], voroshilov:[205,318,.12], budyonny:[230,338,.10], beria:[225,42,-.18], kirov:[295,198,.04], zhukov:[315,70,.20], churchill:[475,52,.16], roosevelt:[505,76,.18], khrushchev:[625,118,-.22], brezhnev:[655,94,-.24], gorbachev:[690,70,-.26], trotsky:[210,650,184,.05,.18], bukharin:[250,610,210,.28,-.12], zinoviev:[285,580,232,.46,.08], tukhachevsky:[260,630,164,.62,.22], hitler:[260,920,46,.30,.95] };
  const visualParent = { yezhov:'beria', comintern:'stalin', rokossovsky:'zhukov', konev:'zhukov' };
  const categories = [['all','全星系','#f0c96a'],['inheritance','理论星云',palette.inheritance],['organization','组织近轨',palette.organization],['conflict','斗争彗云',palette.conflict],['war','战争星云',palette.war],['legacy','遗产远云',palette.legacy],['event','事件脉冲',palette.event],['belt','人民星带',palette.belt]];
  const projection = entities.map((entity, index) => { const spec = layout[entity.id]; const parent = visualParent[entity.id]; const base = { ...entity, type: entity.celestialType, desc: entity.summary, orgs: entity.organizations, events: entity.events, parent, visualParent: parent };
    if (entity.id === 'stalin') return { ...base, orbit:{ type:'core' } };
    if (entity.celestialType === 'comet') return { ...base, orbit:{ type:'comet', periapsis:spec[0], apoapsis:spec[1], angle:spec[2], phase:spec[3], inclination:spec[4], speed:.014 } };
    if (entity.celestialType === 'moon') return { ...base, orbit:{ type:'satellite', radius: entity.id === 'yezhov' ? 42 : entity.id === 'comintern' ? 55 : entity.id === 'rokossovsky' ? 52 : 66, angle: index * 57, speed:.045, tilt:.15 } };
    if (entity.celestialType === 'asteroid') return { ...base, belt:'people-belt', angle:index * 43, orbit:{ type:'belt' } };
    const fallback = [360, index * 41, .08]; const values = spec || fallback; return { ...base, orbit:{ type:'stellar', radius:values[0], angle:values[1], plane:values[2], speed:.008 } };
  });
  return { schemaVersion:'3.0-icm-atlas', scope, palette, sources, sourceMap, sourceKinds, biographyDataUrl:'../../../data/masters/stalin/biography.json', entities, relations, entityById:new Map(entities.map(entity => [entity.id, entity])), relationsByEntity:new Map(entities.map(entity => [entity.id, relations.filter(relation => relation.source === entity.id || relation.target === entity.id)])), categories, typeLabels:{star:'恒星',mentor:'导师恒星',planet:'行星',comet:'彗星',moon:'卫星',asteroid:'知识节点',asteroidBelt:'小行星带',nebula:'历史场域'}, routeCaptions:{all:'全星系观测：人物、组织、事件、文本与地点以不同天体语法共同导航。',inheritance:'理论星云：理论继承与文本入口被投射为远距引力。',organization:'组织近轨：党、国家与国际组织形成制度结构。',conflict:'斗争彗云：冲突关系和争议内容保留来源与审阅状态。',war:'战争星云：人物、组织、事件和外交关系共同呈现。',legacy:'遗产远云：后斯大林时代的继承、否定与解体。',event:'事件脉冲：事件是可进入的上下文，不再只是一行标签。',belt:'人民星带：群体、文本和地点可以作为高亮知识节点进入。'}, nebulae:[{id:'inheritance-nebula',name:'理论继承星云',group:'inheritance',angle:260,distance:430,width:520,height:260,z:-130,desc:'理论、文本与政治继承的前置引力场。'},{id:'conflict-nebula',name:'路线斗争彗云',group:'conflict',angle:205,distance:390,width:520,height:300,z:20,desc:'路线分歧、审判与清洗争议的可审阅历史场域。'},{id:'organization-nebula',name:'组织治理暗云',group:'organization',angle:20,distance:270,width:360,height:210,z:-30,desc:'党政机器、军事班底和国际组织交织的近轨。'},{id:'war-nebula',name:'战争与外交星云',group:'war',angle:58,distance:510,width:620,height:360,z:90,desc:'卫国战争、指挥、外交和敌对入侵构成的历史场域。'},{id:'legacy-nebula',name:'后斯大林遗产远云',group:'legacy',angle:125,distance:650,width:500,height:270,z:-110,desc:'继承、否定、停滞、改革与解体沉积的远轨。'}], belts:[{id:'people-belt',name:'知识与群体小行星带',group:'belt',inner:405,outer:505,count:260,desc:'事件、文本、地点及未来人民群像都以可扩展的知识节点进入星图。'}], bodies:projection };
})();