const panel = document.getElementById('infoPanel');
const legend = document.getElementById('legend');
const search = document.getElementById('searchBox');
const caption = document.getElementById('caption');
const hud = document.getElementById('hud');
const results = document.getElementById('searchResults');
const resultCount = document.getElementById('resultCount');
const resultHint = document.getElementById('resultHint');
const data = STELLAR_DATA;
let active = 'all';
let selectedId = new URLSearchParams(location.search).get('entity') || data.scope.center;
let year = Number(new URLSearchParams(location.search).get('year')) || 1953;
let playback = null;
let activePath = null;
const missionRoutesEl=document.getElementById('missionRoutes');
const missionStepsEl=document.getElementById('missionSteps');
const missionProgressEl=document.getElementById('missionProgress');
const missionDefinitions=[{id:'life',title:'一颗恒星的形成',description:'从革命者到苏联领导者',steps:[{entity:'stalin',year:1878,label:'观测人物起点'},{entity:'lenin',year:1917,label:'进入革命与政治继承'},{entity:'five-year-plans',year:1928,label:'工业化建设与代价'},{entity:'great-patriotic-war',year:1941,label:'战争与国家动员'}]},{id:'war',title:'战争光锥',description:'从入侵到战后秩序',steps:[{entity:'barbarossa',year:1941,label:'战争开始'},{entity:'moscow-defense',year:1941,label:'莫斯科保卫战'},{entity:'stalingrad-battle',year:1942,label:'战局转折'},{entity:'yalta-conference',year:1945,label:'盟国与战后安排'}]},{id:'legacy',title:'白矮星：未竟的遗产',description:'制度、生活、住房与环境',steps:[{entity:'stalin',year:1954,label:'切换至逝世后的遗产观测'},{entity:'soviet-institutions',year:1954,label:'制度与国家能力'},{entity:'housing-design',year:1954,label:'标准化住宅草案'},{entity:'consumer-price-cuts',year:1954,label:'消费品价格政策'},{entity:'nature-transformation-plan',year:1954,label:'环境治理计划'}]}];
let missionState={active:null,progress:{}};
const timeSlider = document.getElementById('timeSlider');
const timeLabel = document.getElementById('timeLabel');
const timeState = document.getElementById('timeState');
const timePlay = document.getElementById('timePlay');
const pathStart = document.getElementById('pathStart');
const pathEnd = document.getElementById('pathEnd');
const pathOutput = document.getElementById('pathOutput');
const relationLayers = document.getElementById('relationLayers');
const relationStatus = document.getElementById('relationStatus');
const reviewState={data:null,filter:'all',entityId:null};
const reviewFilters=[['all','全部段落'],['historical-record','历史记录'],['author-judgment','作者判断'],['historical-dramatization','历史演绎'],['pending','待核验']];
let reviewRequest=0;
let archiveLayer='entity';
let historyMode=false;
const historyToggle=document.getElementById('historyToggle'),missionWindow=document.getElementById('missionWindow'),missionLaunch=document.getElementById('missionLaunch');
const compareA=document.getElementById('compareA'),compareB=document.getElementById('compareB'),compareOutput=document.getElementById('compareOutput');
const lifeTrack=document.getElementById('lifeTrack'),lifeTrackState=document.getElementById('lifeTrackState');
const personIds=data.entities.filter(item=>item.kind==='person').map(item=>item.id);
const knowledgeIds=data.entities.filter(item=>['event','text','place','organization'].includes(item.kind)).map(item=>item.id);
const spaceDefinitions={war:{kind:'field',title:'战争与外交星云',subtitle:'入侵、动员、指挥与战后安排',ids:['stalin','hitler','zhukov','rokossovsky','konev','churchill','roosevelt','red-army','barbarossa','great-patriotic-war','moscow-defense','stalingrad-battle','yalta-conference','postwar-reconstruction','moscow']},conflict:{kind:'field',title:'路线斗争彗云',subtitle:'路线分歧、清洗争议与组织后果',ids:['stalin','trotsky','bukharin','zinoviev','kirov','beria','yezhov','tukhachevsky','great-purge','collectivization-famine','bureaucratic-governance']},legacy:{kind:'field',title:'后斯大林遗产远云',subtitle:'继承、否定、制度与未竟计划',ids:['stalin','khrushchev','brezhnev','gorbachev','soviet-institutions','bureaucratic-governance','postwar-reconstruction','housing-design','consumer-price-cuts','nature-transformation-plan','shelter-policy','postwar-price-cuts','forest-belt-plan']},belt:{kind:'belt',title:'知识与群体小行星带',subtitle:'文本、事件、组织与地点的可展开知识节点',ids:knowledgeIds}};
const eraDefinitions=[{id:'revolution',kind:'era',title:'革命形成',years:'1913—1927',description:'理论文本、革命组织与政治继承',ids:['stalin','lenin','trotsky','zinoviev','molotov','voroshilov','budyonny','comintern','marxism-national-question','foundations-leninism','moscow']},{id:'construction',kind:'era',title:'工业化与集体化',years:'1928—1940',description:'计划建设、路线争议与制度转折',ids:['stalin','trotsky','bukharin','zinoviev','kirov','tukhachevsky','beria','yezhov','industrialization','five-year-plans','collectivization-famine','great-purge','bureaucratic-governance']},{id:'war-era',kind:'era',title:'卫国战争',years:'1941—1945',description:'入侵、动员、指挥、外交与胜利',ids:spaceDefinitions.war.ids},{id:'postwar-era',kind:'era',title:'战后与遗产',years:'1945—1991',description:'重建、生活政策、制度继承与解体',ids:spaceDefinitions.legacy.ids.concat(['great-patriotic-war','yalta-conference'])}];
let spaceState={id:null,parentView:null,eraId:null};
const eraToggle=document.getElementById('eraToggle'),eraBrowser=document.getElementById('eraBrowser'),eraRegions=document.getElementById('eraRegions');
const navTarget=document.getElementById('navTarget'),navTargetName=document.getElementById('navTargetName'),navTargetDistance=document.getElementById('navTargetDistance'),navTargetScope=document.getElementById('navTargetScope'),targetPointer=document.getElementById('targetPointer'),targetPointerName=document.getElementById('targetPointerName');
let navigationTarget=null;
let persistedNavigation={};try{persistedNavigation=JSON.parse(localStorage.getItem('icm-starmap-navigation-v1'))||{};}catch{}
const viewStates=persistedNavigation.views||{};
const lifeMoments=[{year:1878,entity:'stalin',label:'出生与早年'},{year:1898,entity:'stalin',label:'进入革命运动'},{year:1917,entity:'lenin',label:'十月革命与政治继承'},{year:1922,entity:'stalin',label:'中央总书记'},{year:1928,entity:'five-year-plans',label:'工业化转折'},{year:1936,entity:'great-purge',label:'宪法、官僚与清洗争议'},{year:1941,entity:'great-patriotic-war',label:'卫国战争'},{year:1945,entity:'yalta-conference',label:'胜利与战后秩序'},{year:1953,entity:'stalin',label:'死亡与遗产起点'}];
const relationGroups = [{id:'inheritance',label:'理论继承',types:['inheritance']},{id:'organization',label:'组织与同盟',types:['organization','alliance']},{id:'conflict',label:'路线冲突',types:['conflict']},{id:'war',label:'军事与外交',types:['military','diplomacy']},{id:'event',label:'事件光锥',types:['event-participation','event-causation','event-consequence','event-context','event-impact','place-association']},{id:'text',label:'文本与著作',types:['authorship']},{id:'legacy',label:'历史遗产',types:['legacy']}];
let activeRelationGroups = new Set(relationGroups.map(group=>group.id));
const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, match => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[match]));
const typeLabels = { person:'人物', organization:'组织', event:'事件', text:'文本', place:'地点', legacy:'遗产', nebula:'历史场域', asteroidBelt:'知识星带' };
const celestialLabels = data.typeLabels;
const groupLabel = key => data.categories.find(category => category[0] === key)?.[1] || key;
const sourceById = id => data.sources.find(source => source.id === id);
const entityById = id => data.entityById.get(id);
const related = id => data.relationsByEntity.get(id) || [];
const entityText = entity => [entity.id, entity.name, entity.kind, entity.role, entity.years, entity.group, entity.nebula, entity.summary, ...(entity.organizations || []), ...(entity.events || []), ...related(entity.id).map(edge => edge.label)].join(' ').toLowerCase();
const currentScope=()=>spaceState.eraId?eraDefinitions.find(item=>item.id===spaceState.eraId):spaceDefinitions[spaceState.id];
const spaceKey=()=>spaceState.eraId?`era:${spaceState.eraId}`:spaceState.id?`space:${spaceState.id}`:'root';
function saveNavigationState(){viewStates[spaceKey()]=cosmos.getView();try{localStorage.setItem('icm-starmap-navigation-v1',JSON.stringify({spaceId:spaceState.id,eraId:spaceState.eraId,views:viewStates,target:navigationTarget?.id||null}));}catch{}}
function distanceLabel(distance){return distance==null?'位置未知':distance<410?'近距观测 · 已进入边界':distance<550?'中距观测 · 正在接近':'远距观测';}
function targetTelemetry(){if(!navigationTarget)return null;return navigationTarget.kind==='space'?cosmos.regionProjection(navigationTarget.spaceId):cosmos.targetProjection(navigationTarget.id);}
function updateTargetTelemetry(){if(!navigationTarget)return;const telemetry=targetTelemetry(),distance=telemetry?.distance??(navigationTarget.kind==='space'?navigationTarget.distance:cosmos.targetDistance(navigationTarget.id));navTargetDistance.textContent=distanceLabel(distance);const enter=document.getElementById('navTargetEnter'),ready=navigationTarget.kind==='space'&&distance<410;enter.hidden=navigationTarget.kind!=='space';enter.disabled=!ready;enter.textContent=ready?'进入场域':'继续接近';if(!telemetry){targetPointer.hidden=true;return;}const cx=innerWidth/2,cy=innerHeight/2,angle=Math.atan2(telemetry.y-cy,telemetry.x-cx),edge=42,x=Math.max(edge,Math.min(innerWidth-edge,telemetry.x)),y=Math.max((document.querySelector('.site-header')?.offsetHeight||0)+74,Math.min(innerHeight-80,telemetry.y));targetPointer.hidden=telemetry.onScreen;targetPointer.style.left=`${x}px`;targetPointer.style.top=`${y}px`;targetPointer.style.transform=`translate(-50%,-50%) rotate(${angle}rad)`;targetPointer.style.setProperty('--counter-rotation',`${-angle}rad`);targetPointerName.textContent=navigationTarget.name;}
function setNavigationTarget(target){navigationTarget=target;if(!target){navTarget.hidden=true;targetPointer.hidden=true;cosmos.setFocus(null,[]);return;}navTarget.hidden=false;navTargetName.textContent=target.name;navTargetScope.textContent=currentScope()?.title||data.scope.title;const distance=target.kind==='space'?target.distance:cosmos.targetDistance(target.id);navTargetDistance.textContent=distanceLabel(distance);const enter=document.getElementById('navTargetEnter');enter.hidden=target.kind!=='space';enter.disabled=true;enter.dataset.space=target.spaceId||'';saveNavigationState();setTimeout(updateTargetTelemetry,0);}
function locateNavigationTarget(){if(!navigationTarget)return;if(navigationTarget.kind==='space'){const telemetry=cosmos.regionProjection(navigationTarget.spaceId);if(telemetry){cosmos.navigate('zoom-in',.28);}}else cosmos.locate(navigationTarget.id);navTargetDistance.textContent='正在定位目标';setTimeout(()=>{updateTargetTelemetry();saveNavigationState();},700);}
function dispatchNavigation(command,amount=.09){cosmos.navigate(command,amount);updateTargetTelemetry();saveNavigationState();}
const matches = entity => (!currentScope()||currentScope().ids.includes(entity.id)||Boolean(spaceState.eraId&&entity.kind==='person')) && (active === 'all' || entity.group === active || (active === 'belt' && ['event','text','place'].includes(entity.kind))) && (!search.value.trim() || entityText(entity).includes(search.value.trim().toLowerCase())) && (!historyMode || Boolean(spaceState.eraId) || entity.kind === 'person' || entity.kind === 'place' || entity.activeFrom == null || year >= entity.activeFrom);
function loadMissionState(){try{missionState=JSON.parse(localStorage.getItem('icm-starmap-missions-v1'))||missionState;}catch{} }
function saveMissionState(){try{localStorage.setItem('icm-starmap-missions-v1',JSON.stringify(missionState));}catch{}}
function renderMissionSteps(){missionLaunch.querySelector('span').textContent=missionState.active?'当前任务':'任务';const mission=missionDefinitions.find(item=>item.id===missionState.active);missionRoutesEl.innerHTML=missionDefinitions.map(item=>`<button type="button" class="mission-route${missionState.active===item.id?' is-active':''}" data-mission="${item.id}"><b>${item.title}</b><small>${item.description}</small></button>`).join('');missionRoutesEl.querySelectorAll('[data-mission]').forEach(button=>button.addEventListener('click',()=>startMission(button.dataset.mission)));if(!mission){missionProgressEl.textContent='选择一条路线';missionStepsEl.innerHTML='<p>沿着人物、事件与遗产路线探索星图；进度保存在本机。</p>';document.getElementById('missionTarget').innerHTML='<p>尚未选择任务。</p>';cosmos.setMission([],null);return;}const progress=missionState.progress[mission.id]||{visited:[]};const firstUnvisited=mission.steps.findIndex((_,i)=>!progress.visited.includes(i));const index=firstUnvisited<0?mission.steps.length-1:firstUnvisited;const step=mission.steps[index];missionProgressEl.textContent=`${new Set(progress.visited).size} / ${mission.steps.length} 已观测`;const target=entityById(step.entity);document.getElementById('missionTarget').innerHTML=`<div class="mission-target-card"><strong>${esc(target?.name||step.entity)}</strong><span>${esc(step.year+' · '+step.label)}</span><p>${esc(target?.summary||'进入当前目标继续探索。')}</p><button type="button" id="missionTargetGo">前往目标</button></div>`;missionStepsEl.innerHTML=`<div class="mission-intro">${mission.description}</div><ol>${mission.steps.map((item,i)=>`<li class="${progress.visited.includes(i)?'is-visited':''} ${i===index?'is-current':''}"><button type="button" data-step="${i}"><span class="mission-state">${progress.visited.includes(i)?'✓':i===index?'◉':'○'}</span><b>${esc(entityById(item.entity)?.name||item.entity)}</b><small>${esc(item.year+' · '+item.label)}</small></button></li>`).join('')}</ol><div class="mission-actions"><button type="button" id="missionNext">${index===mission.steps.length-1?'完成路线':'前往当前目标'}</button><button type="button" id="missionExit">退出路线</button></div>`;document.getElementById('missionTargetGo').addEventListener('click',()=>{visitMissionStep(index);missionWindow.classList.add('is-minimized');openArchive();});missionStepsEl.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>visitMissionStep(Number(button.dataset.step))));missionStepsEl.querySelector('#missionNext').addEventListener('click',()=>visitMissionStep(index));missionStepsEl.querySelector('#missionExit').addEventListener('click',()=>{missionState.active=null;saveMissionState();renderMissionSteps();});const current=entityById(step.entity);cosmos.setMission(mission.steps.map(item=>item.entity),step.entity);if(current)cosmos.setFocus(current.id,related(current.id).slice(0,4).map(edge=>edge.source===current.id?edge.target:edge.source));}
function startMission(id){const mission=missionDefinitions.find(item=>item.id===id);if(!mission)return;missionState.active=id;missionState.progress[id] ||= {visited:[]};saveMissionState();const firstUnvisited=mission.steps.findIndex((_,i)=>!missionState.progress[id].visited.includes(i));renderMissionSteps();visitMissionStep(firstUnvisited<0?mission.steps.length-1:firstUnvisited);}
function visitMissionStep(index){const mission=missionDefinitions.find(item=>item.id===missionState.active);if(!mission)return;const step=mission.steps[index];if(!step)return;const state=missionState.progress[mission.id]||{visited:[]};if(!state.visited.includes(index))state.visited.push(index);state.visited.sort((a,b)=>a-b);missionState.progress[mission.id]=state;saveMissionState();if(step.year) setYear(step.year);selectEntity(step.entity,false);renderMissionSteps();}
function writeLocation() { const url = new URL(location.href); url.searchParams.set('entity', selectedId); url.searchParams.set('filter', active); url.searchParams.set('year', year); history.replaceState({}, '', url); }
function setYear(nextYear) { year = Math.max(1878, Math.min(1991, Number(nextYear))); timeSlider.value = year; timeLabel.textContent = historyMode ? `观测年份：${year}` : '历史观测：关闭'; if(missionState.active){const m=missionDefinitions.find(item=>item.id===missionState.active),p=missionState.progress[missionState.active]||{visited:[]},step=m?.steps.find(item=>item.year===year);if(step){const stepIndex=m.steps.indexOf(step);if(!p.visited.includes(stepIndex)){p.visited.push(stepIndex);missionState.progress[missionState.active]=p;saveMissionState();renderMissionSteps();}}} const current = entityById(selectedId); timeState.textContent = !historyMode ? '关系导航模式' : current?.deathDate && year >= current.deathDate ? '遗产与历史影响视图' : '历史导航视图'; const lifecycle=document.getElementById('lifecycleState'); if(lifecycle) lifecycle.textContent=current?.deathDate&&year>=current.deathDate?'白矮星 / 遗产观测':current?.kind==='event'?'事件脉冲':'活动期观测'; const coneYear=document.getElementById('coneYear'); if(coneYear) coneYear.textContent=`${year} 年观测`; const archiveLive=document.getElementById('archiveLive'); if(archiveLive&&current?.kind==='event'){archiveLive.innerHTML=renderCone(current);archiveLive.querySelectorAll('[data-cone-entity]').forEach(button=>button.addEventListener('click',()=>selectEntity(button.dataset.coneEntity,true)));} if(current?.kind==='person'&&current.deathDate&&((year>=current.deathDate)!==Boolean(panel.querySelector('.legacy-cabinet')))){renderDetail(current);} renderLifeTrack();cosmos.setYear(year); writeLocation(); apply(); applyRelationLayers(); }
function togglePlayback() { if (playback) { clearInterval(playback); playback = null; timePlay.textContent = '▶ 播放'; timePlay.setAttribute('aria-pressed', 'false'); timeState.textContent = '历史导航视图'; return; } timePlay.textContent = 'Ⅱ 暂停'; timePlay.setAttribute('aria-pressed', 'true'); timeState.textContent = '时间快进中'; playback = setInterval(() => { if (year >= 1991) { togglePlayback(); return; } setYear(year + 1); }, 180); }
function yearRange(value) { const years = String(value || '').match(/\d{4}/g)?.map(Number) || []; return [years[0] || -Infinity, years[1] || years[0] || Infinity]; }
function relationGroupOf(edge) { return relationGroups.find(group=>group.types.includes(edge.type))?.id || 'organization'; }
function relationAvailable(edge) { const [from] = yearRange(edge.period),source=entityById(edge.source),target=entityById(edge.target),personRelation=source?.kind==='person'&&target?.kind==='person'; return activeRelationGroups.has(relationGroupOf(edge)) && (!historyMode || Boolean(spaceState.eraId) || personRelation || year >= from); }
function renderRelationLayers(){relationLayers.innerHTML=relationGroups.map(group=>{const count=data.relations.filter(edge=>group.types.includes(edge.type)).length;return `<button type="button" data-relation-group="${group.id}" aria-pressed="${activeRelationGroups.has(group.id)}" class="${activeRelationGroups.has(group.id)?'is-active':''}">${group.label}<small>${count}</small></button>`;}).join('');relationLayers.querySelectorAll('[data-relation-group]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.relationGroup;if(activeRelationGroups.has(key)&&activeRelationGroups.size>1)activeRelationGroups.delete(key);else activeRelationGroups.add(key);renderRelationLayers();applyRelationLayers();}));relationStatus.textContent=activeRelationGroups.size===relationGroups.length?'显示全部历史关系':`已启用 ${activeRelationGroups.size} / ${relationGroups.length} 层`;}
function applyRelationLayers(){const scope=currentScope(),scopeIds=scope?new Set(spaceState.eraId?[...personIds,...scope.ids]:scope.ids):null;const edges=data.relations.filter(edge=>relationAvailable(edge)&&(!scopeIds||(scopeIds.has(edge.source)&&scopeIds.has(edge.target))));cosmos.setRelations(edges);if(activePath)renderPath(findPath(pathStart.value,pathEnd.value));}
function findPath(startId, endId, maxIntermediates = 6) { if (startId === endId) return { nodes:[startId], edges:[] }; const scope=currentScope(),allowed=scope?new Set(spaceState.eraId?[...personIds,...scope.ids]:scope.ids):null,queue=[{id:startId,nodes:[startId],edges:[]}], visited=new Set([startId]); while(queue.length){const current=queue.shift();if(current.nodes.length>maxIntermediates+1)continue;for(const edge of related(current.id).filter(relationAvailable)){const next=edge.source===current.id?edge.target:edge.source;if(allowed&&!allowed.has(next))continue;if(visited.has(next))continue;const candidate={id:next,nodes:[...current.nodes,next],edges:[...current.edges,edge]};if(next===endId)return candidate;visited.add(next);queue.push(candidate);}}return null; }
function coneGroups(entityId){const incident=related(entityId),roles={precursor:[],participant:[],consequence:[],impact:[],context:[]};for(const edge of incident){const [from]=yearRange(edge.period),source=entityById(edge.source),target=entityById(edge.target),personRelation=source?.kind==='person'&&target?.kind==='person';if((historyMode&&!personRelation&&year<from)||!activeRelationGroups.has(relationGroupOf(edge)))continue;const otherId=edge.source===entityId?edge.target:edge.source;let role=edge.coneRole||'context';if(['event-causation','event-consequence','event-impact'].includes(edge.type)){if(edge.source===entityId)role=edge.type==='event-causation'?'consequence':edge.type==='event-impact'?'impact':'consequence';else role=edge.type==='event-causation'?'precursor':edge.type==='event-impact'?'impact':'precursor';}if(role==='long-term-impact')role='impact';(roles[role]||roles.context).push({edge,entity:entityById(otherId)});}return roles;}
function renderCone(entity){if(!entity||entity.kind!=='event')return '';const groups=coneGroups(entity.id),labels={precursor:'前因与条件',participant:'参与者',consequence:'直接后果',impact:'长期影响',context:'同期关系'};return `<div class="cone-panel"><div class="cone-head"><strong>事件光锥</strong><span>${esc(entity.years||'时期待补')} · <b id="coneYear">${year} 年观测</b></span></div><p class="cone-intro">以事件为中心，分开展示形成条件、参与者、后果与远期影响。光锥表示资料中的导航关系，不等同于唯一因果解释。</p><div class="cone-axis"><span>← 前因</span><i></i><b>${esc(entity.name)}</b><i></i><span>影响 →</span></div><div class="cone-groups">${Object.entries(groups).filter(([,items])=>items.length).map(([key,items])=>`<section><h3>${labels[key]}</h3>${items.map(({edge,entity:other})=>`<button type="button" data-cone-entity="${esc(other.id)}" class="cone-node"><b>${esc(other.name)}</b><span>${esc(edge.label)} · ${esc(edge.period||'时期待补')}${edge.controversy?' · 争议/待复核':''}</span></button>`).join('')}</section>`).join('')||'<p>该事件的光锥关系仍待整理。</p>'}</div></div>`;}
function renderPath(path) { activePath=path; cosmos.setPath(path?.nodes || [], path?.edges || []); if(!path){pathOutput.innerHTML='<p>在当前年份和资料范围内没有找到六人路径。可调整年份后重试。</p>';return;} const route=path.nodes.map((id,index)=>{const entity=entityById(id);const edge=path.edges[index];return `<button type="button" data-path-entity="${esc(id)}"><b>${esc(entity?.name||id)}</b>${edge?`<span>${esc(edge.label)} · ${esc(edge.period||'时期待补')}${edge.controversy?' · 争议':''}</span>`:''}</button>`;}).join('<i>→</i>'); pathOutput.innerHTML=`<p>${path.edges.length} 跳联系 · ${Math.max(0,path.nodes.length-2)} 个中间节点</p><div class="path-route">${route}</div>`;pathOutput.querySelectorAll('[data-path-entity]').forEach(button=>button.addEventListener('click',()=>selectEntity(button.dataset.pathEntity,true))); }
function populatePathSelectors(){const options=data.entities.filter(entity=>(!currentScope()||currentScope().ids.includes(entity.id)||(spaceState.eraId&&entity.kind==='person'))&&(entity.kind!=='place'||entity.id==='moscow')).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN')).map(entity=>`<option value="${esc(entity.id)}">${esc(entity.name)} · ${esc(typeLabels[entity.kind]||entity.kind)}</option>`).join('');pathStart.innerHTML=options;pathEnd.innerHTML=options;pathStart.value=spaceState.id==='belt'?'industrialization':'stalin';pathEnd.value=spaceState.id==='war'||spaceState.eraId==='war-era'?'great-patriotic-war':spaceState.id==='conflict'||spaceState.eraId==='construction'?'great-purge':spaceState.id==='legacy'||spaceState.eraId==='postwar-era'?'khrushchev':spaceState.eraId==='revolution'?'lenin':spaceState.id==='belt'?'five-year-plans':'khrushchev';}
function renderLifeTrack(){const current=lifeMoments.reduce((found,item)=>item.year<=year?item:found,lifeMoments[0]);lifeTrackState.textContent=`${current.year} · ${current.label}`;lifeTrack.innerHTML=lifeMoments.map(item=>`<button type="button" data-life-year="${item.year}" data-life-entity="${item.entity}" class="${item.year<year?'is-past':item.year===current.year?'is-current':'is-future'}"><i></i><b>${item.year}</b><span>${item.label}</span></button>`).join('');lifeTrack.querySelectorAll('[data-life-year]').forEach(button=>button.addEventListener('click',()=>{setYear(button.dataset.lifeYear);selectEntity(button.dataset.lifeEntity,true);}));}
function populateCompare(){const options=data.entities.filter(item=>(!currentScope()||currentScope().ids.includes(item.id)||(spaceState.eraId&&item.kind==='person'))&&(item.kind==='person'||item.kind==='event'||item.kind==='legacy')).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN')).map(item=>`<option value="${esc(item.id)}">${esc(item.name)} · ${esc(typeLabels[item.kind])}</option>`).join('');compareA.innerHTML=options;compareB.innerHTML=options;compareA.value=spaceState.id==='belt'?'industrialization':'stalin';compareB.value=spaceState.id==='war'||spaceState.eraId==='war-era'?'zhukov':spaceState.id==='conflict'||spaceState.eraId==='construction'?'trotsky':spaceState.id==='legacy'||spaceState.eraId==='postwar-era'?'khrushchev':spaceState.eraId==='revolution'?'lenin':spaceState.id==='belt'?'five-year-plans':'lenin';renderCompare();}
function commonRelations(a,b){const aTargets=new Set(related(a.id).map(edge=>edge.source===a.id?edge.target:edge.source));return related(b.id).map(edge=>edge.source===b.id?edge.target:edge.source).filter(id=>aTargets.has(id)).map(entityById).filter(Boolean);}
function renderCompare(){const a=entityById(compareA.value),b=entityById(compareB.value);if(!a||!b)return;const common=commonRelations(a,b);const card=item=>`<article><strong>${esc(item.name)}</strong><span>${esc(typeLabels[item.kind]||item.kind)} · ${esc(item.years||'时期未定')}</span><p>${esc(item.role||item.nebula)}</p><button type="button" data-compare-open="${esc(item.id)}">打开档案</button></article>`;compareOutput.innerHTML=`<div class="compare-cards">${card(a)}${card(b)}</div><p class="compare-boundary">并置只比较现有图谱字段，不构成人物能力或价值排名。</p><div class="compare-common"><strong>共同关系节点</strong>${common.length?common.slice(0,6).map(item=>`<button type="button" data-compare-open="${esc(item.id)}">${esc(item.name)}</button>`).join(''):'<span>当前资料与年份下未整理出共同节点。</span>'}</div>`;compareOutput.querySelectorAll('[data-compare-open]').forEach(button=>button.addEventListener('click',()=>selectEntity(button.dataset.compareOpen,true)));}
function tags(items) { return items?.length ? `<div class="detail-tags">${items.map(item => `<span>${esc(item)}</span>`).join('')}</div>` : '<p class="detail-muted">暂无已整理条目。</p>'; }
function linkList(items) { return items?.length ? `<div class="source-links">${items.map(id => { const source = sourceById(id); return source ? `<a href="${esc(source.href)}" target="_blank" rel="noopener">${esc(source.kind)}：${esc(source.title)} <small>${esc(source.status)}</small></a>` : ''; }).join('')}</div>` : '<p class="detail-muted">来源链接待补。</p>'; }
function mappedParagraphs(entity){return (data.sourceMap[entity.id]||[]).map(([sectionId,paragraphId])=>{const section=reviewState.data?.sections?.find(item=>item.id===sectionId),paragraph=section?.paragraphs?.find(item=>item.id===paragraphId);return section&&paragraph?{section,paragraph}:null;}).filter(Boolean);}
function renderSourceReview(entity){const mount=document.getElementById('sourceReview');if(!mount)return;reviewState.entityId=entity.id;const request=++reviewRequest;const refs=data.sourceMap[entity.id]||[];if(!refs.length){mount.innerHTML='<div class="source-review-empty">尚未映射到具体段落；可从专题入口阅读相关章节。</div>';return;}if(!reviewState.data){mount.innerHTML='<p class="source-review-loading">正在读取候选传记段落…</p>';fetch(data.biographyDataUrl).then(response=>{if(!response.ok)throw new Error('HTTP '+response.status);return response.json();}).then(json=>{reviewState.data=json;if(request===reviewRequest&&reviewState.entityId===entity.id)renderSourceReview(entity);}).catch(()=>{if(request===reviewRequest)mount.innerHTML='<p class="source-review-empty">结构化段落暂不可用，请打开专题章节查看。</p>';});return;}const items=mappedParagraphs(entity),filtered=items.filter(({paragraph})=>reviewState.filter==='all'||(reviewState.filter==='pending'?paragraph.annotationStatus!=='verified':paragraph.annotation===reviewState.filter));const filters=reviewFilters.map(([key,label])=>`<button type="button" class="review-filter${reviewState.filter===key?' is-active':''}" data-review-filter="${key}" aria-pressed="${reviewState.filter===key}">${label}<small>${key==='all'?items.length:key==='pending'?items.filter(item=>item.paragraph.annotationStatus!=='verified').length:items.filter(item=>item.paragraph.annotation===key).length}</small></button>`).join('');mount.innerHTML=`<p class="review-notice">${esc(reviewState.data.readingGuide.notice)} 全部段落与标注均为候选稿内容，非独立史料核验结论。</p><div class="review-filters" role="group" aria-label="筛选段落类型">${filters}</div><div class="review-items">${filtered.map(({section,paragraph})=>`<article class="review-item"><div class="review-meta"><span>${esc(section.title)} · ${esc(paragraph.id)}</span><b>${esc(data.sourceKinds[paragraph.annotation]||paragraph.annotation)} · ${esc(paragraph.annotationStatus==='candidate'?'待审阅':'待核验')}</b></div><blockquote>${esc(paragraph.text)}</blockquote><a href="biography.html#${esc(paragraph.id)}" target="_blank" rel="noopener">打开原文段落 ↗</a></article>`).join('')||'<p class="source-review-empty">此实体没有该类型的已映射段落。</p>'}</div>`;mount.querySelectorAll('[data-review-filter]').forEach(button=>button.addEventListener('click',()=>{reviewState.filter=button.dataset.reviewFilter;renderSourceReview(entity);}));}
function openArchive(){panel.classList.add('is-open');panel.setAttribute('aria-hidden','false');document.getElementById('archiveHandle').setAttribute('aria-expanded','true');}
function closeArchive(){panel.classList.remove('is-open');panel.setAttribute('aria-hidden','true');document.getElementById('archiveHandle').setAttribute('aria-expanded','false');}
function selectEntity(id, focus = false) { const entity = entityById(id); if (!entity) return; selectedId = id;if(focus||navigationTarget)setNavigationTarget({id:entity.id,name:entity.name,kind:'entity'}); writeLocation(); renderDetail(entity); panel.scrollTop=0; renderResults(); if(focus)openArchive(); }
function renderDetail(entity) {
  const color=data.palette[entity.group]||data.palette.belt,edges=related(entity.id),portrait=entity.id==='stalin'?' has-portrait style="--portrait-url:url(../../../images/masters/stalin-star.jpg)"':'';
  cosmos.setFocus(entity.id,edges.slice().sort((a,b)=>(b.strength||0)-(a.strength||0)).slice(0,5).map(edge=>edge.source===entity.id?edge.target:edge.source));
  const connections=edges.map(edge=>{const other=entityById(edge.source===entity.id?edge.target:edge.source);return `<button type="button" class="relation-link" data-entity="${esc(other?.id||'')}"><b>${esc(edge.label)}</b><span>${esc(other?.name||'待补实体')} · ${esc(edge.period||'时期待补')}${edge.controversy?' · 争议':''}</span></button>`;}).join('')||'<p class="detail-muted">该实体的关系边仍待整理。</p>';
  const legacyView=entity.deathDate&&year>=entity.deathDate,lifecycleLabel=legacyView?'白矮星 / 遗产观测':entity.kind==='event'?'事件脉冲':'活动期观测';
  const legacyTopics=[{label:'国家与制度',ids:['soviet-institutions','bureaucratic-governance']},{label:'经济与重建',ids:['postwar-reconstruction','consumer-price-cuts']},{label:'住房与人民生活',ids:['housing-design','consumer-price-cuts']},{label:'环境治理',ids:['nature-transformation-plan']}];
  const legacyItems=legacyView?legacyTopics.map(topic=>`<section><h3>${topic.label}</h3>${topic.ids.map(id=>entityById(id)).filter(Boolean).map(item=>`<button type="button" class="legacy-item" data-entity="${esc(item.id)}"><b>${esc(item.name)}</b><span>${esc(item.role)} · ${esc(item.reviewStatus)}</span></button>`).join('')}</section>`).join(''):'';
  panel.style.setProperty('--detail-color',color);
  panel.innerHTML=`<button class="archive-close" data-archive-close type="button" aria-label="关闭实体档案">×</button><nav class="archive-tabs" aria-label="档案层级"><button type="button" data-archive-layer="entity" class="${archiveLayer==='entity'?'is-active':''}">天体档案</button><button type="button" data-archive-layer="relations" class="${archiveLayer==='relations'?'is-active':''}">关系档案</button><button type="button" data-archive-layer="sources" class="${archiveLayer==='sources'?'is-active':''}">资料档案</button></nav><div class="archive-layer archive-layer-entity ${archiveLayer==='entity'?'is-active':''}"><div class="detail-topline"><span class="detail-kicker">ICM Atlas Archive</span><span class="detail-group">${esc(typeLabels[entity.kind]||entity.kind)} · ${esc(groupLabel(entity.group))}</span></div><div class="detail-celestial"><div class="detail-orb${portrait}"></div><div class="detail-name"><h2>${esc(entity.name)}</h2><p class="detail-role">${esc(entity.role||'关系实体')}</p></div></div><p class="detail-summary">${esc(entity.summary)}</p><div class="detail-block"><strong>图谱定位</strong><p><span class="meta-label">TYPE</span> ${esc(celestialLabels[entity.celestialType]||entity.celestialType)}　<span class="meta-label">TIME</span> ${esc(entity.years||'待补')}　<span class="meta-label">FIELD</span> ${esc(entity.nebula)}</p><p class="detail-muted">当前生命周期：${esc(lifecycleLabel)}。审阅状态：${esc(entity.reviewStatus)}。天体类型仅表达导航语法，不等同于历史从属关系。</p>${entity.perspectiveNote?`<p class="perspective-note">观点与证据提示：${esc(entity.perspectiveNote)}</p>`:''}</div>${legacyView?`<div class="detail-block legacy-cabinet"><strong>遗产展柜</strong><p>以下条目是可继续追踪的主题入口；作者解释、史实记录与待核验主张需分别阅读。</p><div>${legacyItems}</div></div>`:''}</div><div class="archive-layer archive-layer-relations ${archiveLayer==='relations'?'is-active':''}">${entity.kind==='event'?'<div id="archiveLive">':''}${renderCone(entity)}${entity.kind==='event'?'</div>':''}<div class="detail-block"><strong>组织与事件</strong>${tags(entity.organizations)}${tags(entity.events)}</div><div class="detail-block"><strong>关系引力</strong><div class="relation-list">${connections}</div></div></div><div class="archive-layer archive-layer-sources ${archiveLayer==='sources'?'is-active':''}"><div class="detail-block source-review-block"><strong>资料审阅</strong><p>原文观点、叙述和标注均来自候选稿；按认识类型筛选后，可直达章节与具体段落。</p><div id="sourceReview"></div></div><div class="detail-block"><strong>资料与文献入口</strong>${linkList(entity.sourceIds)}</div><div class="detail-block scope-block"><strong>认识边界</strong><p>本图谱提供基于现有候选资料的导航视角，不能概括历史人物的全部面向，也不构成唯一评价。</p></div></div>`;
  renderSourceReview(entity);panel.querySelector('[data-archive-close]')?.addEventListener('click',closeArchive);panel.querySelectorAll('[data-archive-layer]').forEach(button=>button.addEventListener('click',()=>{archiveLayer=button.dataset.archiveLayer;panel.querySelectorAll('[data-archive-layer]').forEach(item=>item.classList.toggle('is-active',item.dataset.archiveLayer===archiveLayer));panel.querySelectorAll('.archive-layer').forEach(layer=>layer.classList.toggle('is-active',layer.classList.contains('archive-layer-'+archiveLayer)));panel.scrollTop=0;}));panel.querySelectorAll('[data-entity],[data-cone-entity]').forEach(button=>button.addEventListener('click',()=>selectEntity(button.dataset.entity||button.dataset.coneEntity,true)));
}
function renderResults() { const list=data.entities.filter(matches).sort((a,b)=>a.kind.localeCompare(b.kind,'zh-CN')||a.name.localeCompare(b.name,'zh-CN'));resultCount.textContent=search.value.trim()?`${list.length} 个匹配实体`:`${list.length} 个可观测实体`;resultHint.textContent=active==='all'?'按类别筛选或检索':groupLabel(active);results.innerHTML=list.length?list.map(entity=>`<button type="button" class="result-item${entity.id===selectedId?' is-active':''}" data-result="${esc(entity.id)}" role="listitem"><i style="background:${data.palette[entity.group]||data.palette.belt}"></i><span><b>${esc(entity.name)}</b><small>${esc(typeLabels[entity.kind]||entity.kind)} · ${esc(entity.role||groupLabel(entity.group))}</small></span></button>`).join(''):'<p class="empty-results">没有匹配实体。可清除检索词或切换观测层。</p>';results.querySelectorAll('[data-result]').forEach(button=>button.addEventListener('click',()=>selectEntity(button.dataset.result,true))); }
const cosmos=new Cosmos(document.getElementById('cosmos'),data,body=>selectEntity(body.id,true));cosmos.onViewChange=view=>{viewStates[spaceKey()]=view;updateTargetTelemetry();try{localStorage.setItem('icm-starmap-navigation-v1',JSON.stringify({spaceId:spaceState.id,eraId:spaceState.eraId,views:viewStates,target:navigationTarget?.id||null}));}catch{}};
function localLayout(ids,kind='field'){const positions={};if(kind==='belt'){const groups=[ids.filter(id=>['text','organization'].includes(entityById(id)?.kind)),ids.filter(id=>entityById(id)?.group==='event'||['industrialization','five-year-plans'].includes(id)),ids.filter(id=>entityById(id)?.group==='war'),ids.filter(id=>entityById(id)?.group==='legacy'),ids.filter(id=>!['text','organization'].includes(entityById(id)?.kind)&&!['event','war','legacy'].includes(entityById(id)?.group))];groups.forEach((items,row)=>items.forEach((id,index)=>{const angle=((index+1)/(items.length+1)*Math.PI*1.5)-Math.PI*.75,radius=155+row*72;positions[id]={x:Math.cos(angle)*radius,y:(row-2)*42,z:Math.sin(angle)*radius};}));return positions;}const center=ids.includes('stalin')?'stalin':ids[0];positions[center]={x:0,y:0,z:0};ids.filter(id=>id!==center).forEach((id,index,items)=>{const ring=index<5?190:index<10?320:430,slot=index<5?index:index<10?index-5:index-10,total=index<5?5:index<10?5:Math.max(1,items.length-10),angle=(slot/total*Math.PI*2)-Math.PI/2;positions[id]={x:Math.cos(angle)*ring,y:Math.sin(angle*2)*34,z:Math.sin(angle)*ring};});return positions;}
function renderSpaceNav(){const def=currentScope();document.body.classList.toggle('in-subspace',Boolean(def));document.body.classList.toggle('in-belt',def?.kind==='belt');document.body.classList.toggle('in-era',Boolean(spaceState.eraId));document.getElementById('spaceTitle').textContent=def?.title||'总览';const visibleCount=def?(spaceState.eraId?new Set([...personIds,...def.ids]).size:def.ids.length):data.entities.length;document.getElementById('spaceCount').textContent=`${visibleCount} 个实体`;document.getElementById('spaceExit').hidden=!def;document.getElementById('spaceExit').textContent=spaceState.eraId?'退出时代区域':'返回母星系';document.getElementById('fieldPortals').hidden=Boolean(def);document.getElementById('fieldHeading').hidden=!def;document.getElementById('beltKey').hidden=def?.kind!=='belt';document.getElementById('fieldTitle').textContent=def?.title||'';document.getElementById('fieldSubtitle').textContent=def?.subtitle||def?.description||'';document.querySelector('.brand b').textContent=def?.title||data.scope.title;}
function enterSpace(id){const def=spaceDefinitions[id];if(!def)return;viewStates[spaceKey()]=cosmos.getView();if(!spaceState.id&&!spaceState.eraId)spaceState.parentView=cosmos.getView();spaceState.id=id;spaceState.eraId=null;cosmos.setTemporalFilter(historyMode);active='all';search.value='';closeArchive();cosmos.setScope(def.ids,localLayout(def.ids,def.kind));const restored=viewStates[spaceKey()];if(restored)cosmos.setView(restored);else{cosmos.resetView();cosmos.zoom=innerWidth<600?.82:1.15;}renderSpaceNav();populatePathSelectors();populateCompare();apply();applyRelationLayers();saveNavigationState();}
function exitSpace(){if(!spaceState.id&&!spaceState.eraId)return;viewStates[spaceKey()]=cosmos.getView();spaceState.id=null;spaceState.eraId=null;cosmos.setTemporalFilter(historyMode);cosmos.setScope(null,null);cosmos.setView(viewStates.root||spaceState.parentView);setNavigationTarget(null);renderSpaceNav();populatePathSelectors();populateCompare();apply();applyRelationLayers();saveNavigationState();}
function renderEraBrowser(){eraRegions.innerHTML=eraDefinitions.map(item=>`<button type="button" class="era-region${spaceState.eraId===item.id?' is-active':''}" data-era="${item.id}"><span>${item.years}</span><strong>${item.title}</strong><small>${item.description}</small></button>`).join('');eraRegions.querySelectorAll('[data-era]').forEach(button=>button.addEventListener('click',()=>enterEra(button.dataset.era)));}
function enterEra(id){const era=eraDefinitions.find(item=>item.id===id);if(!era)return;viewStates[spaceKey()]=cosmos.getView();if(!spaceState.id&&!spaceState.eraId)spaceState.parentView=cosmos.getView();spaceState.id=null;spaceState.eraId=id;cosmos.setTemporalFilter(false);active='all';search.value='';closeArchive();const ids=[...new Set([...personIds,...era.ids])];cosmos.setScope(ids,localLayout(ids,'field'));const restored=viewStates[spaceKey()];if(restored)cosmos.setView(restored);else{cosmos.resetView();cosmos.zoom=innerWidth<600?.82:1.05;}eraBrowser.hidden=true;eraToggle.setAttribute('aria-expanded','false');renderSpaceNav();populatePathSelectors();populateCompare();apply();applyRelationLayers();saveNavigationState();}
function apply() { cosmos.setFilter(active,search.value);caption.textContent=data.routeCaptions[active]||data.routeCaptions.all;document.querySelectorAll('.legend button').forEach(button=>button.classList.toggle('is-active',button.dataset.key===active));renderResults();writeLocation(); }
for(const [key,label,color] of data.categories){const button=document.createElement('button');button.dataset.key=key;button.type='button';button.innerHTML=`<i style="background:${color}"></i>${label}`;button.addEventListener('click',()=>{active=key;apply();});legend.appendChild(button);}
search.addEventListener('input',apply);
compareA.addEventListener('change',renderCompare);compareB.addEventListener('change',renderCompare);document.getElementById('compareUseCurrent').addEventListener('click',()=>{if(compareA.value===selectedId)compareB.value=selectedId;else compareA.value=selectedId;renderCompare();});
document.getElementById('resetView').addEventListener('click',()=>{active='all';search.value='';selectedId=data.scope.center;cosmos.resetView();setYear(1953);selectEntity(selectedId);});document.querySelectorAll('[data-enter-space]').forEach(button=>{button.addEventListener('click',()=>{const id=button.dataset.enterSpace,def=spaceDefinitions[id],region=data.nebulae.find(item=>item.group===id);setNavigationTarget({id:`space:${id}`,name:def.title,kind:'space',spaceId:id,distance:region?.distance||430});});button.addEventListener('dblclick',()=>enterSpace(button.dataset.enterSpace));});document.getElementById('spaceExit').addEventListener('click',exitSpace);document.getElementById('spaceHome').addEventListener('click',exitSpace);
timeSlider.addEventListener('input',event=>setYear(event.target.value));
timePlay.addEventListener('click',togglePlayback);
document.getElementById('timeBack').addEventListener('click',()=>setYear(year-10));
document.getElementById('timeForward').addEventListener('click',()=>setYear(year+10));
document.getElementById('timeReset').addEventListener('click',()=>setYear(1953));eraToggle.addEventListener('click',()=>{const opening=eraBrowser.hidden;eraBrowser.hidden=!opening;eraToggle.setAttribute('aria-expanded',String(opening));renderEraBrowser();});document.getElementById('eraClose').addEventListener('click',()=>{eraBrowser.hidden=true;eraToggle.setAttribute('aria-expanded','false');});document.getElementById('eraReset').addEventListener('click',()=>{exitSpace();eraBrowser.hidden=true;eraToggle.setAttribute('aria-expanded','false');});historyToggle.addEventListener('click',()=>{historyMode=!historyMode;historyToggle.setAttribute('aria-pressed',String(historyMode));historyToggle.querySelector('span').textContent=historyMode?'关闭历史':'历史观测';document.getElementById('timeDrawer').hidden=!historyMode;cosmos.setTemporalFilter(historyMode&&!spaceState.eraId);setYear(year);});missionLaunch.addEventListener('click',()=>{missionWindow.hidden=false;missionLaunch.setAttribute('aria-expanded','true');missionWindow.classList.add('is-open');});document.getElementById('missionClose').addEventListener('click',()=>{missionWindow.hidden=true;missionLaunch.setAttribute('aria-expanded','false');missionWindow.classList.remove('is-open');});document.getElementById('missionMinimize').addEventListener('click',()=>missionWindow.classList.toggle('is-minimized'));
function makeDraggable(windowEl,handle){let drag=null;handle.addEventListener('pointerdown',event=>{if(event.target.closest('button')||innerWidth<760)return;const rect=windowEl.getBoundingClientRect();drag={x:event.clientX,y:event.clientY,left:rect.left,top:rect.top};handle.setPointerCapture(event.pointerId);});handle.addEventListener('pointermove',event=>{if(!drag)return;const left=Math.max(8,Math.min(innerWidth-windowEl.offsetWidth-8,drag.left+event.clientX-drag.x)),top=Math.max(8,Math.min(innerHeight-windowEl.offsetHeight-8,drag.top+event.clientY-drag.y));windowEl.style.left=`${left}px`;windowEl.style.top=`${top}px`;windowEl.style.right='auto';windowEl.style.bottom='auto';windowEl.style.transform='none';});handle.addEventListener('pointerup',()=>{drag=null;});}makeDraggable(missionWindow,document.getElementById('missionDragHandle'));document.querySelectorAll('.tool-window').forEach(item=>makeDraggable(item,item.querySelector('header')));
document.getElementById('relationReset').addEventListener('click',()=>{activeRelationGroups=new Set(relationGroups.map(group=>group.id));renderRelationLayers();applyRelationLayers();});
document.getElementById('pathFind').addEventListener('click',()=>renderPath(findPath(pathStart.value,pathEnd.value)));
document.getElementById('pathUseSelected').addEventListener('click',()=>{pathStart.value=selectedId;renderPath(findPath(pathStart.value,pathEnd.value));});
document.getElementById('pathSwap').addEventListener('click',()=>{const start=pathStart.value;pathStart.value=pathEnd.value;pathEnd.value=start;if(activePath)renderPath(findPath(pathStart.value,pathEnd.value));});
document.getElementById('pathClear').addEventListener('click',()=>{activePath=null;cosmos.setPath([],[]);pathOutput.innerHTML='<p>选择两个实体，寻找不超过六个中间节点的历史联系。</p>';});
document.querySelectorAll('[data-nav-command]').forEach(button=>{let timer=null;const run=()=>dispatchNavigation(button.dataset.navCommand,.07);button.addEventListener('pointerdown',event=>{event.preventDefault();run();timer=setInterval(run,75);button.setPointerCapture(event.pointerId);});const stop=()=>{clearInterval(timer);timer=null;};button.addEventListener('pointerup',stop);button.addEventListener('pointercancel',stop);});document.getElementById('navTargetLocate').addEventListener('click',locateNavigationTarget);document.getElementById('navTargetClear').addEventListener('click',()=>setNavigationTarget(null));document.getElementById('navTargetEnter').addEventListener('click',event=>{if(navigationTarget?.spaceId&&!event.currentTarget.disabled)enterSpace(navigationTarget.spaceId);});document.getElementById('deepMode').addEventListener('click',event=>{const on=!document.body.classList.contains('deep-space');document.body.classList.toggle('deep-space',on);event.currentTarget.classList.toggle('is-active',on);event.currentTarget.setAttribute('aria-pressed',String(on));});
document.querySelectorAll('[data-tool]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.tool,windowEl=document.querySelector(`[data-tool-window="${id}"]`),opening=windowEl.hidden;document.querySelectorAll('[data-tool-window]').forEach(item=>item.hidden=true);document.querySelectorAll('[data-tool]').forEach(item=>item.setAttribute('aria-pressed','false'));if(opening){windowEl.hidden=false;button.setAttribute('aria-pressed','true');}}));document.querySelectorAll('[data-tool-close]').forEach(button=>button.addEventListener('click',()=>{button.closest('[data-tool-window]').hidden=true;document.querySelectorAll('[data-tool]').forEach(item=>item.setAttribute('aria-pressed','false'));}));document.getElementById('archiveHandle').addEventListener('click',openArchive);document.getElementById('archiveClose').addEventListener('click',closeArchive);document.getElementById('homeView').addEventListener('click',()=>{exitSpace();eraBrowser.hidden=true;eraToggle.setAttribute('aria-expanded','false');cosmos.resetView();closeArchive();});search.addEventListener('focus',()=>document.getElementById('searchPopover').classList.add('is-open'));document.addEventListener('pointerdown',event=>{const pop=document.getElementById('searchPopover');if(!event.target.closest('.global-search')&&!event.target.closest('#searchPopover'))pop.classList.remove('is-open');});
active=new URLSearchParams(location.search).get('filter')||'all';if(persistedNavigation.eraId)spaceState.eraId=persistedNavigation.eraId;else if(persistedNavigation.spaceId)spaceState.id=persistedNavigation.spaceId;renderEraBrowser();renderSpaceNav();populatePathSelectors();populateCompare();renderLifeTrack();renderRelationLayers();loadMissionState();renderMissionSteps();timeSlider.value=year;if(spaceState.eraId){const era=eraDefinitions.find(item=>item.id===spaceState.eraId),ids=[...new Set([...personIds,...era.ids])];cosmos.setScope(ids,localLayout(ids,'field'));cosmos.setTemporalFilter(false);cosmos.setView(viewStates[spaceKey()]||cosmos.getView());}else if(spaceState.id){const def=spaceDefinitions[spaceState.id];cosmos.setScope(def.ids,localLayout(def.ids,def.kind));cosmos.setTemporalFilter(historyMode);cosmos.setView(viewStates[spaceKey()]||cosmos.getView());}setYear(year);selectEntity(entityById(selectedId)?selectedId:data.scope.center);if(persistedNavigation.target && persistedNavigation.target!=='space:war' && persistedNavigation.target!=='space:conflict' && persistedNavigation.target!=='space:legacy' && persistedNavigation.target!=='space:belt'){const target=entityById(persistedNavigation.target);if(target)setNavigationTarget({id:target.id,name:target.name,kind:'entity'});}if(persistedNavigation.target){const target=entityById(persistedNavigation.target);if(target)setNavigationTarget({id:target.id,name:target.name,kind:'entity'});}
