class Cosmos {
  constructor(canvas, data, onPick) {
    this.c = canvas; this.ctx = canvas.getContext('2d'); this.data = data; this.onPick = onPick; this.onViewChange = null;
    this.yaw = .42; this.pitch = -.34; this.zoom = 1; this.viewTarget = null; this.t = 0; this.drag = null; this.points = []; this.positions = new Map(); this.labelRects = [];
    this.filter = 'all'; this.query = ''; this.temporalFilter = false; this.scopeIds = null; this.localPositions = null; this.running = true; this.reducedMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
    this.bodyById = new Map(data.bodies.map(body => [body.id, body])); this.beltById = new Map(data.belts.map(belt => [belt.id, belt]));
    this.portrait = new Image(); this.portrait.src = '../../../images/masters/stalin-star.jpg'; this.makeDust(); this.makeBeltDust(); this.bind(); this.resize(); requestAnimationFrame(() => this.frame());
  }
  setFilter(filter, query) { this.filter = filter || 'all'; this.query = (query || '').toLowerCase(); }
  setYear(year) { this.year = Number(year) || 1953; }
  setTemporalFilter(enabled) { this.temporalFilter=Boolean(enabled); }
  getView() { return { yaw:this.yaw,pitch:this.pitch,zoom:this.zoom }; }
  setView(view) { if(!view)return;this.yaw=view.yaw;this.pitch=view.pitch;this.zoom=view.zoom;this.viewTarget=null; }
  notifyViewChange() { if(this.onViewChange)this.onViewChange(this.getView()); }
  navigate(command, amount=.08) { this.viewTarget=null;if(command==='yaw-left')this.yaw-=amount;if(command==='yaw-right')this.yaw+=amount;if(command==='pitch-up')this.pitch=Math.max(-.78,this.pitch-amount);if(command==='pitch-down')this.pitch=Math.min(.32,this.pitch+amount);if(command==='zoom-in')this.zoom=Math.min(1.75,this.zoom+amount);if(command==='zoom-out')this.zoom=Math.max(.62,this.zoom-amount);this.notifyViewChange(); }
  targetProjection(id) { const body=this.bodyById.get(id);if(!body)return null;const point=this.project(this.bodyPos(body));return {...point,onScreen:this.safe(point)&&point.x>70&&point.x<innerWidth-70&&point.y>90&&point.y<innerHeight-90}; }
  locate(id) { const body=this.bodyById.get(id);if(!body)return false;const pos=this.bodyPos(body),angle=Math.atan2(pos.z,pos.x),horizontal=Math.hypot(pos.x,pos.z),pitch=Math.max(-.7,Math.min(.2,-Math.atan2(pos.y,horizontal||1)));this.viewTarget={yaw:Math.PI/2-angle,pitch,zoom:Math.max(1.15,this.zoom)};return true; }
  targetDistance(id) { const body=this.bodyById.get(id);if(!body)return null;const pos=this.bodyPos(body);return Math.hypot(pos.x,pos.y,pos.z)/Math.max(.62,this.zoom); }
  regionProjection(group) { const region=this.data.nebulae.find(item=>item.group===group),position=region?this.regionPos(region):group==='belt'?{x:0,y:0,z:455}:null;if(!position)return null;const point=this.project(position),distance=(region?.distance||455)/Math.max(.62,this.zoom);return {...point,onScreen:this.safe(point)&&point.x>70&&point.x<innerWidth-70&&point.y>90&&point.y<innerHeight-90,distance}; }
  setScope(ids = null, positions = null) { this.scopeIds=ids?new Set(ids):null;this.localPositions=positions?new Map(Object.entries(positions)):null;this.focusId=null;this.focusIds=null;this.setPath([],[]); }
  setPath(nodes, edges) { this.pathNodes = new Set(nodes || []); this.pathEdges = edges || []; }
  setRelations(edges) { this.relationEdges = edges || []; }
  setFocus(id, relatedIds = []) { this.focusId=id; this.focusIds=new Set([id,...relatedIds]); }
  setMission(ids = [], target = null) { this.missionIds=new Set(ids); this.missionTarget=target; }
  resetView() { this.yaw = .42; this.pitch = -.34; this.zoom = 1; }
  visible(object) {
    const route = this.filter === 'all' || object.group === this.filter || (this.filter === 'belt' && ['asteroid','asteroidBelt'].includes(object.type));
    const text = [object.id,object.name,object.role,object.rank,object.nebula,object.desc,...(object.orgs || []),...(object.events || [])].join(' ').toLowerCase();
    const activeAtYear = !this.temporalFilter || object.type==='star' || object.type==='mentor' || object.type==='planet' || object.type==='comet' || object.activeFrom == null || this.year == null || this.year >= object.activeFrom;
    return (!this.scopeIds||this.scopeIds.has(object.id)) && route && activeAtYear && (!this.query || text.includes(this.query));
  }
  makeDust() { this.dust = Array.from({ length: 900 }, () => { const far = Math.random() < .62, radius = far ? 900 + Math.random() * 1600 : 80 + Math.pow(Math.random(), .65) * 760, angle = Math.random() * Math.PI * 2; return { x:Math.cos(angle)*radius, y:(Math.random()-.5)*(far?900:420), z:Math.sin(angle)*radius, s:(far?.45:.75)+Math.random()*1.15, h:Math.random(), far }; }); }
  makeBeltDust() { this.beltDust = this.data.belts.flatMap(belt => Array.from({ length:belt.count }, () => { const angle = Math.random()*Math.PI*2, radius = belt.inner + Math.random()*(belt.outer-belt.inner); return { belt, angle, radius, offset:(Math.random()-.5)*20, size:Math.random()*1.7+.35 }; })); }
  bind() {
    addEventListener('resize', () => this.resize()); addEventListener('visibilitychange', () => { this.running = !document.hidden; if (this.running) requestAnimationFrame(() => this.frame()); });
    this.c.addEventListener('pointerdown', event => { this.c.setPointerCapture(event.pointerId); this.drag = { id:event.pointerId, x:event.clientX, y:event.clientY, yaw:this.yaw, pitch:this.pitch, moved:false }; });
    this.c.addEventListener('pointermove', event => { if (!this.drag || event.pointerId !== this.drag.id) return; const dx = event.clientX-this.drag.x, dy = event.clientY-this.drag.y; this.drag.moved ||= Math.hypot(dx,dy) > 4; this.yaw = this.drag.yaw + dx*.006; this.pitch = Math.max(-.78,Math.min(.32,this.drag.pitch + dy*.004));this.notifyViewChange(); });
    const release = event => { if (this.drag?.id === event.pointerId) this.drag = null; }; this.c.addEventListener('pointerup', release); this.c.addEventListener('pointercancel', release);
    this.c.addEventListener('wheel', event => { event.preventDefault(); this.zoom = Math.max(.62,Math.min(1.75,this.zoom-event.deltaY*.001));this.notifyViewChange(); }, { passive:false });
    this.c.addEventListener('click', event => { const hit = this.points.filter(point => Math.hypot(point.x-event.clientX,point.y-event.clientY)<point.hit).sort((a,b) => b.priority-a.priority || b.depth-a.depth)[0]; if (hit) this.onPick(hit.body); });
  }
  resize() { const dpr = Math.min(devicePixelRatio || 1, 2); this.c.width = innerWidth*dpr; this.c.height = innerHeight*dpr; this.c.style.width = `${innerWidth}px`; this.c.style.height = `${innerHeight}px`; this.ctx.setTransform(dpr,0,0,dpr,0,0); }
  project(point) { const cy=Math.cos(this.yaw),sy=Math.sin(this.yaw),cp=Math.cos(this.pitch),sp=Math.sin(this.pitch); let x=point.x*cy-point.z*sy,z=point.x*sy+point.z*cy,y=point.y*cp-z*sp; z=point.y*sp+z*cp+1500/this.zoom; const clipped=z<90; z=Math.max(90,z); const factor=680/z*this.zoom; return { x:innerWidth/2+x*factor, y:innerHeight/2+y*factor, scale:Math.max(0,Math.min(3,factor)), depth:1/z, clipped }; }
  rgb(hex) { const value=parseInt(hex.replace('#',''),16); return `${value>>16&255},${value>>8&255},${value&255}`; }
  colorOf(object) { return this.rgb(this.data.palette[object.group] || this.data.palette.belt); }
  safe(point) { return Number.isFinite(point.x) && Number.isFinite(point.y) && !point.clipped; }
  glow(x,y,r,rgb,alpha=1) { if (!Number.isFinite(r) || r<=0) return; const gradient=this.ctx.createRadialGradient(x,y,0,x,y,r); gradient.addColorStop(0,`rgba(${rgb},${alpha})`); gradient.addColorStop(.3,`rgba(${rgb},${alpha*.32})`); gradient.addColorStop(1,`rgba(${rgb},0)`); this.ctx.fillStyle=gradient; this.ctx.beginPath(); this.ctx.arc(x,y,r,0,Math.PI*2); this.ctx.fill(); }
  planePoint(angle,radius,plane=0) { return { x:Math.cos(angle)*radius, y:Math.sin(angle)*radius*4*plane, z:Math.sin(angle)*radius }; }
  tiltPoint(x,y,z,tilt=0) { const c=Math.cos(tilt),s=Math.sin(tilt); return { x, y:y*c-z*s, z:y*s+z*c }; }
  orbitPoint(orbit, staticOnly=false) { if (!orbit || orbit.type==='core') return {x:0,y:0,z:0}; if (orbit.type==='stellar') { const angle=orbit.angle*Math.PI/180+(staticOnly||this.reducedMotion?0:this.t*orbit.speed*.45); return this.planePoint(angle,orbit.radius,orbit.plane||0); } if (orbit.type==='comet') { const u=orbit.phase*7+(staticOnly||this.reducedMotion?0:this.t*orbit.speed*3.2), rotation=orbit.angle*Math.PI/180, a=(orbit.apoapsis+orbit.periapsis)/2, b=Math.sqrt(orbit.apoapsis*orbit.periapsis)*.5, c=a-orbit.periapsis, x=Math.cos(u)*a-c,z=Math.sin(u)*b; return this.tiltPoint(x*Math.cos(rotation)-z*Math.sin(rotation),0,x*Math.sin(rotation)+z*Math.cos(rotation),orbit.inclination||0); } return {x:0,y:0,z:0}; }
  bodyPos(body) { if(this.localPositions?.has(body.id))return this.localPositions.get(body.id); if (body.orbit?.type==='satellite') { const parent=this.bodyById.get(body.visualParent), parentPos=this.bodyPos(parent), angle=body.orbit.angle*Math.PI/180+(this.reducedMotion?0:this.t*body.orbit.speed*7), radius=body.orbit.radius; return { x:parentPos.x+Math.cos(angle)*radius,y:parentPos.y+Math.sin(angle)*radius*(.48+(body.orbit.tilt||0)),z:parentPos.z+Math.sin(angle)*radius }; } if (body.type==='asteroid') { const belt=this.beltById.get(body.belt), angle=(body.angle||0)*Math.PI/180+(this.reducedMotion?0:this.t*.003), radius=(belt.inner+belt.outer)/2; return {x:Math.cos(angle)*radius,y:0,z:Math.sin(angle)*radius}; } return this.orbitPoint(body.orbit); }
  regionPos(region) { const angle=region.angle*Math.PI/180; return { x:Math.cos(angle)*region.distance,y:(region.z||0)*.35,z:Math.sin(angle)*region.distance }; }
  drawBackground() { const ctx=this.ctx, bg=ctx.createRadialGradient(innerWidth*.48,innerHeight*.52,0,innerWidth*.5,innerHeight*.5,Math.max(innerWidth,innerHeight)); bg.addColorStop(0,'#141018'); bg.addColorStop(.44,'#07080d'); bg.addColorStop(1,'#010106'); ctx.fillStyle=bg; ctx.fillRect(0,0,innerWidth,innerHeight); ctx.globalCompositeOperation='lighter'; for (const dust of this.dust) { const point=this.project({x:dust.x,y:dust.y+(this.reducedMotion?0:Math.sin(this.t*.5+dust.h*9)*4),z:dust.z}); if (!this.safe(point)) continue; ctx.fillStyle=`rgba(${dust.h<.5?'80,185,201':dust.h<.78?'169,121,186':'240,201,106'},${(dust.far?.1:.16)*Math.min(1,point.scale*1.6)})`; ctx.beginPath(); ctx.arc(point.x,point.y,dust.s*Math.max(.18,point.scale*1.45),0,Math.PI*2); ctx.fill(); } }
  drawNebulaRegions() { if(this.scopeIds)return; const ctx=this.ctx; ctx.save(); ctx.globalCompositeOperation='screen'; ctx.font='900 11px Microsoft YaHei'; ctx.textAlign='center'; for (const region of this.data.nebulae) { if (!this.visible(region)) continue; const point=this.project(this.regionPos(region)); if (!this.safe(point)) continue; const rgb=this.colorOf(region), rx=Math.max(36,region.width*point.scale*.62),ry=Math.max(22,region.height*point.scale*.38); for(let layer=0;layer<3;layer++){const k=1-layer*.22,gradient=ctx.createRadialGradient(point.x,point.y,0,point.x,point.y,Math.max(rx,ry)*k);gradient.addColorStop(0,`rgba(${rgb},${.13-layer*.025})`);gradient.addColorStop(.55,`rgba(${rgb},${.055-layer*.012})`);gradient.addColorStop(1,`rgba(${rgb},0)`);ctx.fillStyle=gradient;ctx.beginPath();ctx.ellipse(point.x,point.y,rx*k,ry*k,this.yaw*.18+layer*.28,0,Math.PI*2);ctx.fill();} ctx.strokeStyle=`rgba(${rgb},.26)`;ctx.setLineDash([10,12]);ctx.beginPath();ctx.ellipse(point.x,point.y,rx*.75,ry*.6,this.yaw*.18,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(247,234,209,.55)';ctx.fillText(region.name,point.x,point.y-ry*.5); } ctx.restore(); }
  drawOrbitPath(radius, plane=0) { const ctx=this.ctx; ctx.beginPath(); for(let i=0;i<=120;i++){const point=this.project(this.planePoint(i/120*Math.PI*2,radius,plane));if(!this.safe(point))continue;i?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y);}ctx.stroke(); }
  drawOrbits() { if(this.scopeIds)return this.drawLocalOrbits(); const ctx=this.ctx;ctx.save();ctx.globalCompositeOperation='lighter';for(const radius of [170,225,315,455,545,650]){ctx.strokeStyle=radius===455?'rgba(244,226,186,.16)':'rgba(240,201,106,.105)';ctx.lineWidth=radius===455?1.35:1;ctx.setLineDash(radius===455?[3,7]:[]);this.drawOrbitPath(radius);ctx.setLineDash([]);}for(const body of this.data.bodies.filter(body=>body.type==='comet'&&this.visible(body))){ctx.strokeStyle=`rgba(${this.colorOf(body)},.24)`;ctx.setLineDash([8,10]);ctx.beginPath();for(let i=0;i<=110;i++){const point=this.project(this.orbitPoint({...body.orbit,phase:i/110},true));if(!this.safe(point))continue;i?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y);}ctx.stroke();ctx.setLineDash([]);}ctx.restore(); }
  drawLocalOrbits() { const ctx=this.ctx;ctx.save();ctx.strokeStyle='rgba(199,168,93,.11)';ctx.lineWidth=1;for(const radius of [150,270,390])this.drawOrbitPath(radius);ctx.restore(); }
  drawBelt() { if(this.scopeIds)return; if (!(this.filter==='all'||this.filter==='belt'||this.filter==='event'||this.filter==='inheritance'||this.filter==='organization'||this.filter==='war'||this.filter==='conflict')) return; const ctx=this.ctx,belt=this.data.belts[0];ctx.save();ctx.globalCompositeOperation='lighter';for(const radius of [belt.inner,belt.outer,(belt.inner+belt.outer)/2]){ctx.strokeStyle=radius===(belt.inner+belt.outer)/2?'rgba(244,226,186,.16)':'rgba(244,226,186,.06)';ctx.lineWidth=radius===(belt.inner+belt.outer)/2?14:1;this.drawOrbitPath(radius);}for(const dust of this.beltDust){const angle=dust.angle+(this.reducedMotion?0:this.t*.002),point=this.project({x:Math.cos(angle)*dust.radius,y:dust.offset*.25,z:Math.sin(angle)*dust.radius});if(!this.safe(point))continue;ctx.fillStyle=`rgba(244,226,186,${Math.min(.42,point.scale*1.5)})`;ctx.beginPath();ctx.arc(point.x,point.y,dust.size*Math.max(.2,point.scale*1.7),0,Math.PI*2);ctx.fill();}ctx.restore(); }
  drawRelations() { if(!this.relationEdges?.length)return;const ctx=this.ctx;ctx.save();ctx.globalCompositeOperation='screen';for(const edge of this.relationEdges){const source=this.bodyById.get(edge.source),target=this.bodyById.get(edge.target);if(!source||!target||!this.visible(source)||!this.visible(target))continue;const a=this.project(this.bodyPos(source)),b=this.project(this.bodyPos(target));if(!this.safe(a)||!this.safe(b))continue;const years=String(edge.period||'').match(/\d{4}/g)?.map(Number)||[],historical=years[1]&&this.year>years[1],rgb=edge.controversy?'240,120,61':edge.type==='legacy'?'169,121,186':edge.type==='military'||edge.type==='diplomacy'?'80,185,201':'240,201,106';ctx.strokeStyle=`rgba(${rgb},${historical?.09:.2})`;ctx.lineWidth=Math.max(.7,(edge.strength||.5)*1.5);ctx.setLineDash(edge.controversy?[3,7]:historical?[2,9]:[]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}ctx.restore();}
  drawPath() { if(!this.pathEdges?.length)return;const ctx=this.ctx;ctx.save();ctx.globalCompositeOperation='screen';ctx.strokeStyle='rgba(255,238,171,.9)';ctx.lineWidth=2.4;ctx.setLineDash([4,5]);for(const edge of this.pathEdges){const source=this.bodyById.get(edge.source),target=this.bodyById.get(edge.target);if(!source||!target||!this.visible(source)||!this.visible(target))continue;const a=this.project(this.bodyPos(source)),b=this.project(this.bodyPos(target));if(!this.safe(a)||!this.safe(b))continue;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();this.glow(a.x,a.y,18,'240,201,106',.36);this.glow(b.x,b.y,18,'240,201,106',.36);}ctx.restore();}
  drawPortrait(point,radius) { const ctx=this.ctx;this.glow(point.x,point.y,radius*9,'240,201,106',.95);this.glow(point.x,point.y,radius*14,'201,33,53',.36);ctx.save();ctx.beginPath();ctx.arc(point.x,point.y,radius*1.58,0,Math.PI*2);ctx.clip();if(this.portrait.complete){const side=Math.min(this.portrait.width,this.portrait.height)*.62;ctx.drawImage(this.portrait,this.portrait.width*.19,this.portrait.height*.1,side,side,point.x-radius*1.58,point.y-radius*1.58,radius*3.16,radius*3.16);}ctx.restore();ctx.strokeStyle='rgba(240,201,106,.92)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(point.x,point.y,radius*1.62,0,Math.PI*2);ctx.stroke(); }
  drawBodies() { const ctx=this.ctx;this.positions.clear();const visible=this.data.bodies.filter(body=>this.visible(body));const items=visible.filter(body=>body.type!=='moon').map(body=>({body,point:this.project(this.bodyPos(body))})).filter(item=>this.safe(item.point));items.forEach(item=>this.positions.set(item.body.id,item.point));const moons=visible.filter(body=>body.type==='moon').map(body=>({body,point:this.project(this.bodyPos(body))})).filter(item=>this.safe(item.point));const all=items.concat(moons).sort((a,b)=>a.point.depth-b.point.depth);for(const item of all){const {body,point}=item,rgb=this.colorOf(body),isLegacy=body.deathDate && this.year >= body.deathDate,isPathMode=this.pathNodes?.size>0,isOnPath=this.pathNodes?.has(body.id),isMissionMode=this.missionIds?.size>0,isOnMission=this.missionIds?.has(body.id),isMissionTarget=this.missionTarget===body.id,radius=body.size*Math.max(.48,point.scale*2.05)*(isLegacy?.78:1);ctx.save();ctx.globalAlpha=isPathMode&&!isOnPath?.18:isMissionMode&&!isOnMission?.24:1;if(isMissionTarget){this.glow(point.x,point.y,radius*11,'240,201,106',.8);ctx.strokeStyle='rgba(255,238,171,.95)';ctx.lineWidth=2;ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(point.x,point.y,radius*2.4,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}if(body.type==='comet')this.glow(point.x,point.y,radius*7,rgb,.55);if(body.type==='star'&&!isLegacy)this.drawPortrait(point,radius);else{this.glow(point.x,point.y,radius*(isLegacy?7:5.2),rgb,isLegacy?.38:.62);ctx.fillStyle=`rgba(${rgb},${isLegacy?.58:.97})`;ctx.beginPath();ctx.arc(point.x,point.y,radius,0,Math.PI*2);ctx.fill();if(isLegacy){ctx.strokeStyle=`rgba(244,226,186,.72)`;ctx.lineWidth=1.5;ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(point.x,point.y,radius*1.65,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}}const labelPriority=(this.pathNodes?.has(body.id)?3:this.focusIds?.has(body.id)?2:1),mobileLocal=this.scopeIds&&innerWidth<600,labelVisible=labelPriority>1||(!this.focusIds?.size&&(!mobileLocal||body.size>=10||body.id==='stalin'));ctx.fillStyle=`rgba(247,234,209,${body.type==='moon'?.72:isLegacy?.62:.9})`;ctx.font='12px Microsoft YaHei';if(labelVisible){const labelWidth=ctx.measureText(body.name).width,labelX=Math.min(innerWidth-labelWidth-8,point.x+radius+9),labelY=point.y+4,labelRect={left:labelX-2,right:labelX+labelWidth+2,top:labelY-12,bottom:labelY+4},overlap=this.labelRects.some(rect=>labelRect.left<rect.right&&labelRect.right>rect.left&&labelRect.top<rect.bottom&&labelRect.bottom>rect.top);if(!overlap){ctx.fillText(body.name,labelX,labelY);this.labelRects.push(labelRect);}}this.points.push({x:point.x,y:point.y,hit:Math.max(18,radius+12),depth:point.depth,priority:labelPriority,body});ctx.restore();} }
  frame() { if (!this.running) return;if(this.viewTarget){const ease=.09;this.yaw+=(this.viewTarget.yaw-this.yaw)*ease;this.pitch+=(this.viewTarget.pitch-this.pitch)*ease;this.zoom+=(this.viewTarget.zoom-this.zoom)*ease;this.notifyViewChange();if(Math.abs(this.viewTarget.yaw-this.yaw)<.002&&Math.abs(this.viewTarget.pitch-this.pitch)<.002&&Math.abs(this.viewTarget.zoom-this.zoom)<.002)this.viewTarget=null;} this.t+=this.reducedMotion?0:.006; this.points=[];this.labelRects=[];this.ctx.clearRect(0,0,innerWidth,innerHeight);this.drawBackground();this.drawNebulaRegions();this.drawOrbits();this.drawBelt();this.drawRelations();this.drawPath();this.ctx.globalCompositeOperation='lighter';this.drawBodies();this.ctx.globalCompositeOperation='source-over';requestAnimationFrame(()=>this.frame()); }
}
